# list all 3D models in this directory and write them to .gitignore
# because some files are extremely large (exceed 1GB)

import os

root = os.path.dirname(__file__).replace('\\','/')
if root[-1]!='/': root+='/'

def getExtension(path):
    ext = os.path.splitext(path)[1]
    return ext.lstrip('.').lower()

def indexDirectory(_dir):
    ls = [f for f in os.listdir(_dir)]
    files = [_dir+f for f in ls if os.path.isfile(_dir+f)]
    dirs = [_dir+f for f in ls if os.path.isdir(_dir+f)]
    arr = []
    for fn in files:
        if getExtension(fn) in ['stl','ply','blend','raw']:
            arr.append(fn.replace(root,''))
    for path in dirs:
        arr += indexDirectory(path+'/')
    return arr


s = '# generated by index.py\n\n' + '\n'.join(indexDirectory(root))

fp = open('.gitignore', 'w')
fp.write(s)
fp.close()

