var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=(a,b)=>{throw b;},ca="object"==typeof window,k="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ea,fa,ha;
if(da){var fs=require("fs"),ia=require("path");l=k?ia.dirname(l)+"/":__dirname+"/";ea=(a,b)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ha=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};fa=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof ja||a.context instanceof ja))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ba=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(ca||k)k?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
k&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var n=f.print||console.log.bind(console),r=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.quit&&(ba=f.quit);var ka;f.wasmBinary&&(ka=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&v("no native wasm support detected");var la,w=!1,ma,y,z,na,B,C,oa,pa;function qa(){var a=la.buffer;f.HEAP8=y=new Int8Array(a);f.HEAP16=na=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=z=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=C=new Uint32Array(a);f.HEAPF32=oa=new Float32Array(a);f.HEAPF64=pa=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();sa.unshift(a)}
var D=0,xa=null,ya=null;function v(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";r(a);w=!0;ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function za(a){return a.startsWith("data:application/octet-stream;base64,")}var E;E="module.wasm";if(!za(E)){var Aa=E;E=f.locateFile?f.locateFile(Aa,l):l+Aa}function Ba(a){try{if(a==E&&ka)return new Uint8Array(ka);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){v(b)}}
function Ca(a){if(!ka&&(ca||k)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ba(a));if(fa)return new Promise((b,c)=>{fa(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ba(a))}function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r("failed to asynchronously prepare wasm: "+d);v(d)})}
function Ea(a,b){var c=E;ka||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||c.startsWith("file://")||da||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r("wasm streaming compile failed: "+e);r("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Fa(a){for(;0<a.length;)a.shift()(f)}f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a>>0];case "i8":return y[a>>0];case "i16":return na[a>>1];case "i32":return B[a>>2];case "i64":return B[a>>2];case "float":return oa[a>>2];case "double":return pa[a>>3];case "*":return C[a>>2];default:v(`invalid type for getValue: ${b}`)}};var Ga="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?F(z,a,b):""}
function Ha(a){this.ta=a-24;this.Hb=function(b){C[this.ta+4>>2]=b};this.Eb=function(b){C[this.ta+8>>2]=b};this.qa=function(b,c){this.Db();this.Hb(b);this.Eb(c)};this.Db=function(){C[this.ta+16>>2]=0}}var Ia=0,Ja=0,Ka;Ka=da?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function La(a){a instanceof ja||"unwind"==a||ba(1,a)}function Ma(a){ma=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);w=!0}ba(a,new ja(a))}
function Na(a){if(!w)try{if(a(),!noExitRuntime)try{ma=a=ma,Ma(a)}catch(b){La(b)}}catch(b){La(b)}}function Oa(a){setTimeout(()=>{Na(a)},1E4)}var Pa=f.preloadPlugins||[],Qa=!1,H=null,I=0,Ra=null,Sa=0,Ta=0,Ua=0,J=0,Va=[],Wa={},Xa,Ya,Za,$a=!1,ab=!1,bb=[];
function cb(){function a(){ab=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!db){db=!0;Pa.push({canHandle:function(c){return!f.ec&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=new Blob([c],{type:eb(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:eb(d)}));var m=URL.createObjectURL(h),q=new Image;q.onload=()=>{q.complete||v("Image "+
d+" could not be decoded");var p=document.createElement("canvas");p.width=q.width;p.height=q.height;p.getContext("2d").drawImage(q,0,0);URL.revokeObjectURL(m);e&&e(c)};q.onerror=()=>{n("Image "+m+" could not be decoded");g&&g()};q.src=m}});Pa.push({canHandle:function(c){return!f.dc&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){h||(h=!0,e&&e(c))}var h=!1,m=URL.createObjectURL(new Blob([c],{type:eb(d)})),q=new Audio;q.addEventListener("canplaythrough",()=>g(q),!1);
q.onerror=function(){if(!h){r("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var p="",t=0,u=0,x=0;x<c.length;x++)for(t=t<<8|c[x],u+=8;6<=u;){var A=t>>u-6&63;u-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==u?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==u&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");q.src="data:audio/x-"+d.substr(-3)+
";base64,"+p;g(q)}};q.src=m;Oa(()=>{g(q)})}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!ab&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function fb(a,b,c,d){if(b&&f.Aa&&a==f.canvas)return f.Aa;var e;if(b){var g={antialias:!1,alpha:!1,Fb:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof gb&&(e=hb(a,g)))var m=ib[e].Da}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||v("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Aa=m,b&&(L=ib[e],f.Aa=K=L&&L.Da),f.hc=b,bb.forEach(q=>q()),cb());return m}var jb=!1,kb=void 0,M=void 0;
function lb(a,b){function c(){$a=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=mb,kb&&d.requestPointerLock(),$a=!0,M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),nb(f.canvas),ob()):nb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]&-8388609),
nb(f.canvas),ob()):nb(d));if(f.onFullScreen)f.onFullScreen($a);if(f.onFullscreen)f.onFullscreen($a)}kb=a;M=b;"undefined"==typeof kb&&(kb=!0);"undefined"==typeof M&&(M=!1);var d=f.canvas;jb||(jb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function mb(){if(!$a)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var pb=0;
function qb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===pb)pb=b+1E3/60;else for(;b+2>=pb;)pb+=1E3/60;setTimeout(a,Math.max(pb-b,0))}}function eb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var N=0,rb=0,tb=0,ub=0;
function vb(a){if(ab)"mousemove"!=a.type&&"mozMovementX"in a?tb=ub=0:(tb=a.movementX||a.mozMovementX||a.webkitMovementX||0,ub=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(N=SDL.ac+tb,rb=SDL.bc+ub):(N+=tb,rb+=ub);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==a.type&&
"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,tb=e-N,ub=a-rb,N=e,rb=a)}}var wb=[];function ob(){var a=f.canvas;wb.forEach(b=>b(a.width,a.height))}function xb(a,b,c){nb(f.canvas,a,b);c||ob()}
function nb(a,b,c){b&&c?(a.Mb=b,a.Bb=c):(b=a.Mb,c=a.Bb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}M?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var db;
function yb(a,b){Ta=a;Ua=b;if(Ra)if(Qa||(Qa=!0),0==a)H=function(){var d=Math.max(0,Ya+b-Ka())|0;setTimeout(Za,d)};else if(1==a)H=function(){qb(Za)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);k?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}H=function(){setImmediate(Za)}}}
function zb(a,b,c,d,e){!Ra||v("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ra=a;Sa=d;var g=I;Qa=!1;Za=function(){if(!w)if(0<Va.length){var h=Date.now(),m=Va.shift();m.Xb(m.Pb);if(Xa){var q=Xa,p=0==q%1?q-1:Math.floor(q);Xa=m.Sb?p:(8*q+(p+.5))/9}n('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||"Please wait...",
m=Xa,q=Wa.Wb,m?m<q?f.setStatus(h+" ("+(q-m)+"/"+q+")"):f.setStatus(h):f.setStatus(""));g<I||setTimeout(Za,0)}else if(!(g<I))if(J=J+1|0,1==Ta&&1<Ua&&0!=J%Ua)H();else{0==Ta&&(Ya=Ka());if(L)for(h=L.ya,L.ya=L.Ba,L.Ba=h,h=L.ua,L.ua=L.La,L.La=h,h=Ab(2097152),m=0;m<=h;++m)L.ua[m]=0;w||f.preMainLoop&&!1===f.preMainLoop()||(Na(a),f.postMainLoop&&f.postMainLoop());g<I||("object"==typeof SDL&&SDL.audio&&SDL.audio.Jb&&SDL.audio.Jb(),H())}};e||(b&&0<b?yb(0,1E3/b):yb(1,1),H());if(c)throw"unwind";}var Bb=[];
function O(a){var b=Bb[a];b||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=b=ra.get(a));return b}var Cb=[null,[],[]],Db=1,Eb=[],P=[],Q=[],Fb=[],ib=[],Gb=[1,1,2,2,4,4,4,2,3,4,8];function R(a){Hb||(Hb=a)}function Ib(a){for(var b=Db++,c=a.length;c<b;c++)a[c]=null;return b}function Ab(a){return 32-Math.clz32(0===a?0:a-1)}
function hb(a,b){a.qa||(a.qa=a.getContext,a.getContext=function(d,e){e=a.qa(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Jb(c,b):0}
function Jb(a,b){var c=Ib(ib),d={Zb:c,attributes:b,version:b.Fb,Da:a};a.canvas&&(a.canvas.Nb=d);ib[c]=d;("undefined"==typeof b.zb||b.zb)&&Kb(d);d.hb=d.Da.getParameter(34921);d.za=[];for(a=0;a<d.hb;a++)d.za[a]={enabled:!1,Ma:!1,size:0,type:0,mb:0,Ua:0,ta:0,tb:null};a=Ab(2097152);d.ua=[];d.La=[];d.ua.length=d.La.length=a+1;d.ya=[];d.Ba=[];d.ya.length=d.Ba.length=a+1;d.xa=[];d.xa.length=a+1;for(b=0;b<=a;++b){d.xa[b]=null;d.ua[b]=d.La[b]=0;d.ya[b]=[];d.Ba[b]=[];var e=d.ya[b],g=d.Ba[b];e.length=g.length=
64;for(var h=0;64>h;++h)e[h]=g[h]=null}return c}
function Kb(a){a||(a=L);if(!a.Cb){a.Cb=!0;var b=a.Da;b.Vb=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.$b=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.$a=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.$a)b.$a=b.getExtension("EXT_disjoint_timer_query");b.cc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var gb={},Hb,L,Lb;function Mb(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),h=g&&Ib(d);g?(g.name=h,d[h]=g):R(1282);B[b+4*e>>2]=h}}
function Nb(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Ob(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Pb(a){var b=K.yb;if(b){var c=b.Ca[a];"number"==typeof c&&(b.Ca[a]=c=K.getUniformLocation(b,b.rb[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function Qb(a,b,c,d){this.id=a;this.y=this.x=0;this.Ra=!1;this.qb=this.pb=0;this.width=b;this.height=c;this.ob=b;this.nb=c;this.title=d;this.attributes=S;this.buttons=0;this.keys=[];this.Pa=[];this.Xa=this.gb=this.Qa=this.Ka=this.Ea=this.Oa=this.kb=this.ub=this.eb=this.vb=this.title=null}
function Rb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Sb(a){var b=Rb(a)+1,c=Tb(b);c&&Nb(a,z,c,b);return c}function Ub(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(da)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}v("initRandomDevice")}
function Vb(a){return(Vb=Ub())(a)}
var Wb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Xb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Yb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Zb=a=>
{if("/"===a)return"/";a=Xb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function $b(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var ac=[];function bc(a,b){ac[a]={input:[],output:[],wa:b};cc(a,dc)}
var dc={open:function(a){var b=ac[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.wa.fsync(a.tty)},fsync:function(a){a.tty.wa.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.wa.fb)throw new T(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.wa.fb(a.tty)}catch(m){throw new T(29);}if(void 0===h&&0===e)throw new T(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.wa.Sa)throw new T(60);
try{for(var e=0;e<d;e++)a.tty.wa.Sa(a.tty,b[c+e])}catch(g){throw new T(29);}d&&(a.node.timestamp=Date.now());return e}},ec={fb:function(a){if(!a.input.length){var b=null;if(da){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(Rb(b)+1);b=Nb(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Sa:function(a,b){null===b||10===b?(n(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(n(F(a.output,0)),a.output=[])}},fc={Sa:function(a,b){null===b||10===b?(r(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(r(F(a.output,0)),a.output=[])}},U={oa:null,ra:function(){return U.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.oa||(U.oa={dir:{node:{sa:U.la.sa,pa:U.la.pa,lookup:U.la.lookup,Ia:U.la.Ia,rename:U.la.rename,unlink:U.la.unlink,rmdir:U.la.rmdir,readdir:U.la.readdir,symlink:U.la.symlink},stream:{va:U.ma.va}},file:{node:{sa:U.la.sa,pa:U.la.pa},stream:{va:U.ma.va,read:U.ma.read,write:U.ma.write,Wa:U.ma.Wa,ib:U.ma.ib,lb:U.ma.lb}},link:{node:{sa:U.la.sa,pa:U.la.pa,readlink:U.la.readlink},stream:{}},Ya:{node:{sa:U.la.sa,
pa:U.la.pa},stream:gc}});c=hc(a,b,c,d);16384===(c.mode&61440)?(c.la=U.oa.dir.node,c.ma=U.oa.dir.stream,c.ka={}):32768===(c.mode&61440)?(c.la=U.oa.file.node,c.ma=U.oa.file.stream,c.na=0,c.ka=null):40960===(c.mode&61440)?(c.la=U.oa.link.node,c.ma=U.oa.link.stream):8192===(c.mode&61440)&&(c.la=U.oa.Ya.node,c.ma=U.oa.Ya.stream);c.timestamp=Date.now();a&&(a.ka[b]=c,a.timestamp=c.timestamp);return c},Yb:function(a){return a.ka?a.ka.subarray?a.ka.subarray(0,a.na):new Uint8Array(a.ka):new Uint8Array(0)},
ab:function(a,b){var c=a.ka?a.ka.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ka,a.ka=new Uint8Array(b),0<a.na&&a.ka.set(c.subarray(0,a.na),0))},Kb:function(a,b){if(a.na!=b)if(0==b)a.ka=null,a.na=0;else{var c=a.ka;a.ka=new Uint8Array(b);c&&a.ka.set(c.subarray(0,Math.min(b,a.na)));a.na=b}},la:{sa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.na:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wb=4096;b.blocks=Math.ceil(b.size/b.wb);return b},pa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.Kb(a,b.size)},lookup:function(){throw ic[44];},Ia:function(a,b,c,d){return U.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=jc(b,
c)}catch(g){}if(d)for(var e in d.ka)throw new T(55);}delete a.parent.ka[a.name];a.parent.timestamp=Date.now();a.name=c;b.ka[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ka[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=jc(a,b),d;for(d in c.ka)throw new T(55);delete a.ka[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ka)a.ka.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},ma:{read:function(a,b,c,d,e){var g=a.node.ka;if(e>=a.node.na)return 0;a=Math.min(a.node.na-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===y.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ka||a.ka.subarray)){if(g)return a.ka=b.subarray(c,c+d),a.na=d;if(0===a.na&&0===e)return a.ka=b.slice(c,c+d),a.na=
d;if(e+d<=a.na)return a.ka.set(b.subarray(c,c+d),e),d}U.ab(a,e+d);if(a.ka.subarray&&b.subarray)a.ka.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ka[e+g]=b[c+g];a.na=Math.max(a.na,e+d);return d},va:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.na);if(0>b)throw new T(28);return b},Wa:function(a,b,c){U.ab(a.node,b+c);a.node.na=Math.max(a.node.na,b+c)},ib:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.ka;if(e&2||a.buffer!==y.buffer){if(0<
c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;v();b=void 0;if(!b)throw new T(48);y.set(a,b)}else c=!1,b=a.byteOffset;return{ta:b,Ob:c}},lb:function(a,b,c,d){U.ma.write(a,b,0,d,c,!1);return 0}}};function kc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var lc=null,mc={},nc=[],oc=1,pc=null,qc=!0,T=null,ic={},V=(a,b={})=>{a=$b(a);if(!a)return{path:"",node:null};b=Object.assign({cb:!0,Ta:0},b);if(8<b.Ta)throw new T(32);a=a.split("/").filter(h=>!!h);for(var c=lc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=jc(c,a[e]);d=Xb(d+"/"+a[e]);c.Ja&&(!g||g&&b.cb)&&(c=c.Ja.root);if(!g||b.bb)for(g=0;40960===(c.mode&61440);)if(c=rc(d),d=$b(Yb(d),c),c=V(d,{Ta:b.Ta+1}).node,40<g++)throw new T(32);}return{path:d,node:c}},sc=a=>{for(var b;;){if(a===
a.parent)return a=a.ra.jb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},tc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pc.length},jc=(a,b)=>{var c;if(c=(c=uc(a,"x"))?c:a.la.lookup?0:2)throw new T(c,a);for(c=pc[tc(a.id,b)];c;c=c.Ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.la.lookup(a,b)},hc=(a,b,c,d)=>{a=new vc(a,b,c,d);b=tc(a.parent.id,a.name);a.Ib=pc[b];return pc[b]=a},wc=a=>{var b=["r","w","rw"][a&3];
a&512&&(b+="w");return b},uc=(a,b)=>{if(qc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},xc=(a,b)=>{try{return jc(a,b),20}catch(c){}return uc(a,"wx")},yc=()=>{for(var a=0;4096>=a;a++)if(!nc[a])return a;throw new T(33);},Ac=a=>{zc||(zc=function(){this.qa={}},zc.prototype={},Object.defineProperties(zc.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.qa.flags},
set:function(c){this.qa.flags=c}},position:{get:function(){return this.qa.position},set:function(c){this.qa.position=c}}}));a=Object.assign(new zc,a);var b=yc();a.fd=b;return nc[b]=a},gc={open:a=>{a.ma=mc[a.node.rdev].ma;a.ma.open&&a.ma.open(a)},va:()=>{throw new T(70);}},cc=(a,b)=>{mc[a]={ma:b}},Bc=(a,b)=>{var c="/"===b,d=!b;if(c&&lc)throw new T(10);if(!c&&!d){var e=V(b,{cb:!1});b=e.path;e=e.node;if(e.Ja)throw new T(10);if(16384!==(e.mode&61440))throw new T(54);}b={type:a,fc:{},jb:b,Gb:[]};a=a.ra(b);
a.ra=b;b.root=a;c?lc=a:e&&(e.Ja=b,e.ra&&e.ra.Gb.push(b))},W=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=Zb(a);if(!a||"."===a||".."===a)throw new T(28);var e=xc(d,a);if(e)throw new T(e);if(!d.la.Ia)throw new T(63);return d.la.Ia(d,a,b,c)},Cc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},Dc=(a,b)=>{if(!$b(a))throw new T(44);var c=V(b,{parent:!0}).node;if(!c)throw new T(44);b=Zb(b);var d=xc(c,b);if(d)throw new T(d);if(!c.la.symlink)throw new T(63);c.la.symlink(c,b,a)},rc=a=>{a=V(a).node;if(!a)throw new T(44);
if(!a.la.readlink)throw new T(28);return $b(sc(a.parent),a.la.readlink(a))},Fc=(a,b,c)=>{if(""===a)throw new T(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Xb(a);try{e=V(a,{bb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new T(20);}else e=W(a,c,0),d=!0;if(!e)throw new T(44);8192===(e.mode&
61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new T(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==wc(b)||b&512)?31:uc(e,wc(b)):44))throw new T(c);if(b&512&&!d){c=e;c="string"==typeof c?V(c,{bb:!0}).node:c;if(!c.la.pa)throw new T(63);if(16384===(c.mode&61440))throw new T(31);if(32768!==(c.mode&61440))throw new T(28);if(d=uc(c,"w"))throw new T(d);c.la.pa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Ac({node:e,path:sc(e),flags:b,seekable:!0,position:0,ma:e.ma,
Lb:[],error:!1});e.ma.open&&e.ma.open(e);!f.logReadFiles||b&1||(Ec||(Ec={}),a in Ec||(Ec[a]=1));return e},Gc=(a,b,c,d)=>{var e=void 0;if(0>c||0>e)throw new T(28);if(null===a.fd)throw new T(8);if(0===(a.flags&2097155))throw new T(8);if(16384===(a.node.mode&61440))throw new T(31);if(!a.ma.write)throw new T(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new T(8);if(!a.seekable||!a.ma.va)throw new T(70);a.position=a.ma.va(a,0,2);a.Lb=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new T(70);
b=a.ma.write(a,b,0,c,e,d);g||(a.position+=b)},Hc=()=>{T||(T=function(a,b){this.name="ErrnoError";this.node=b;this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(a=>{ic[a]=new T(a);ic[a].stack="<generic error, no stack>"}))},Ic,Jc=()=>{var a="/";a="string"==typeof a?a:sc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=Xb(a+"/"+c);try{W(a,16895,0)}catch(d){}}}},Lc=(a,b,c)=>{a=Xb("/dev/"+a);var d=kc(!!b,!!c);Kc||(Kc=64);var e=Kc++<<8|0;
cc(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,m,q)=>{for(var p=0,t=0;t<q;t++){try{var u=b()}catch(x){throw new T(29);}if(void 0===u&&0===p)throw new T(6);if(null===u||void 0===u)break;p++;h[m+t]=u}p&&(g.node.timestamp=Date.now());return p},write:(g,h,m,q)=>{for(var p=0;p<q;p++)try{c(h[m+p])}catch(t){throw new T(29);}q&&(g.node.timestamp=Date.now());return p}});Cc(a,d,e)},Kc,zc,Ec,X=null,Mc=null,Y=null,S=null,Nc={131073:0,131074:0,131075:1,131076:1,131077:1,
131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Oc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Pc(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Qc(a){X&&X.Xa&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||O(X.Xa)(X.id,a))}function Rc(a,b){if(X){var c=Oc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.Pa[a]=b;X.gb&&(d&&(b=2),O(X.gb)(X.id,c,a,b,Pc()))}}}
function Sc(){Tc()}function Uc(){Tc()}function Vc(a){Rc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Wc(a){Rc(a.keyCode,0)}function Xc(){if(X)for(var a=0;a<X.Pa.length;++a)X.Pa[a]&&Rc(a,0)}function Yc(a){X&&(vb(a),a.target==f.canvas&&X.Oa&&X.Oa&&O(X.Oa)(X.id,N,rb))}function Zc(a){X&&a.target==f.canvas&&X.Ea&&O(X.Ea)(X.id,1)}function $c(a){X&&a.target==f.canvas&&X.Ea&&O(X.Ea)(X.id,0)}
function ad(a,b){if(X&&(vb(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.kb&&O(X.kb)(X.id,c,b,Pc())}}function bd(a){X&&ad(a,1)}function cd(a){X&&ad(a,0)}
function dd(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.Ka&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;O(X.Ka)(X.id,b,c);a.preventDefault()}}
var Z={},ed=[],fd=null;
function Tc(){if(J!==fd||!J){ed=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];fd=J;for(var a=0;a<ed.length;++a){var b=ed[a];if(b){Z[a]||(n("glfw joystick connected:",a),Z[a]={id:Sb(b.id),Rb:b.buttons.length,Qb:b.axes.length,buttons:Tb(b.buttons.length),axes:Tb(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)y[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)oa[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(n("glfw joystick disconnected",
a),gd(Z[a].id),gd(Z[a].buttons),gd(Z[a].axes),delete Z[a])}}}
function hd(a){function b(m){var q="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),p=new FileReader;p.onloadend=u=>{if(2!=p.readyState)++g,n("failed to read dropped file: "+m.name+": "+p.error);else{var x=new Uint8Array(u.target.result);u={};u.flags=u.flags||577;var A=Fc(q,u.flags,u.mode);if("string"==typeof x){var sb=new Uint8Array(Rb(x)+1);x=Nb(x,sb,0,sb.length);Gc(A,sb,x,u.xb)}else if(ArrayBuffer.isView(x))Gc(A,x,x.byteLength,u.xb);else throw Error("Unsupported data type");if(null===A.fd)throw new T(8);
A.Ab&&(A.Ab=null);try{A.ma.close&&A.ma.close(A)}catch(rd){throw rd;}finally{nc[A.fd]=null}A.fd=null;if(++g===e){O(X.Qa)(X.id,e,c);for(u=0;u<d.length;++u)gd(d[u]);gd(c)}}};p.readAsArrayBuffer(m);var t=Sb(q);d.push(t);C[c+4*h>>2]=t}if(X&&X.Qa&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Tb(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Jc();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}
function jd(a){if(X&&X.Qa)return a.preventDefault(),!1}f.requestFullscreen=function(a,b){lb(a,b)};f.requestAnimationFrame=function(a){qb(a)};f.setCanvasSize=function(a,b,c){xb(a,b,c)};f.pauseMainLoop=function(){H=null;I++};f.resumeMainLoop=function(){I++;var a=Ta,b=Ua,c=Ra;Ra=null;zb(c,0,!1,Sa,!0);yb(a,b);H()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return fb(a,b,c,d)};var K;function vc(a,b,c,d){a||(a=this);this.parent=a;this.ra=a.ra;this.Ja=null;this.id=oc++;this.name=b;this.mode=c;this.la={};this.ma={};this.rdev=d}Object.defineProperties(vc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Hc();pc=Array(4096);Bc(U,"/");W("/tmp",16895,0);
W("/home",16895,0);W("/home/web_user",16895,0);(()=>{W("/dev",16895,0);cc(259,{read:()=>0,write:(d,e,g,h)=>h});Cc("/dev/null",259);bc(1280,ec);bc(1536,fc);Cc("/dev/tty",1280);Cc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Vb(a).byteLength);return a[--b]};Lc("random",c);Lc("urandom",c);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();
(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);Bc({ra:()=>{var b=hc(a,"fd",16895,73);b.la={lookup:(c,d)=>{var e=nc[+d];if(!e)throw new T(8);c={parent:null,ra:{jb:"fake"},la:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var kd={i:function(a,b,c,d){v(`Assertion failed: ${G(a)}, at: `+[b?G(b):"unknown filename",c,d?G(d):"unknown function"])},m:function(a,b,c){(new Ha(a)).qa(b,c);Ia=a;Ja++;throw Ia;},E:function(){return!0},k:function(){v("")},G:Ka,H:function(a,b,c){z.copyWithin(a,b,b+c)},D:function(a){var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=la.buffer;try{la.grow(g.call(e,2147483648,
d)-h.byteLength+65535>>>16);qa();var m=1;break a}catch(q){}m=void 0}if(m)return!0}return!1},R:function(a){eval(G(a))},S:function(a,b,c){a=O(a);zb(a,b,c)},F:function(){return 52},C:function(){return 70},q:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=C[b>>2],m=C[b+4>>2];b+=8;for(var q=0;q<m;q++){var p=z[h+q],t=Cb[a];0===p||10===p?((1===a?n:r)(F(t,0)),t.length=0):t.push(p)}e+=m}C[d>>2]=e;return 0},o:function(a,b){K.attachShader(P[a],Q[b])},c:function(a,b){34962==a?K.Za=b:34963==a&&(K.Na=b);35051==
a?K.Tb=b:35052==a&&(K.Ub=b);K.bindBuffer(a,Eb[b])},U:function(a){K.bindVertexArray(Fb[a]);a=K.getParameter(34965);K.Na=a?a.name|0:0},b:function(a,b,c,d){c&&b?K.bufferData(a,z,d,c,b):K.bufferData(a,b,d)},I:function(a){K.clear(a)},J:function(a,b,c,d){K.clearColor(a,b,c,d)},u:function(a){K.compileShader(Q[a])},B:function(){var a=Ib(P),b=K.createProgram();b.name=a;b.Ha=b.Fa=b.Ga=0;b.Va=1;P[a]=b;return a},y:function(a){var b=Ib(Q);Q[b]=K.createShader(a);return b},w:function(a){if(a){var b=Q[a];b?(K.deleteShader(b),
Q[a]=null):R(1281)}},K:function(a){K.depthFunc(a)},x:function(a,b){K.detachShader(P[a],Q[b])},d:function(a){L.za[a].enabled=!1;K.disableVertexAttribArray(a)},r:function(a,b,c,d){if(!K.Na){var e=1*Gb[c-5120]*b;var g=Ab(e);var h=L.xa[g];h?g=h:(h=K.getParameter(34965),L.xa[g]=K.createBuffer(),K.bindBuffer(34963,L.xa[g]),K.bufferData(34963,1<<g,35048),K.bindBuffer(34963,h),g=L.xa[g]);K.bindBuffer(34963,g);K.bufferSubData(34963,0,z.subarray(d,d+e));d=0}Lb=!1;for(e=0;e<L.hb;++e)if(g=L.za[e],g.Ma&&g.enabled){Lb=
!0;h=g.Ua;h=0<h?b*h:g.size*Gb[g.type-5120]*b;var m=Ab(h);var q=L.ya[m],p=L.ua[m];L.ua[m]=L.ua[m]+1&63;var t=q[p];t?m=t:(t=K.getParameter(34964),q[p]=K.createBuffer(),K.bindBuffer(34962,q[p]),K.bufferData(34962,1<<m,35048),K.bindBuffer(34962,t),m=q[p]);K.bindBuffer(34962,m);K.bufferSubData(34962,0,z.subarray(g.ta,g.ta+h));g.tb.call(K,e,g.size,g.type,g.mb,g.Ua,0)}K.drawElements(a,b,c,d);Lb&&K.bindBuffer(34962,Eb[K.Za]);K.Na||K.bindBuffer(34963,null)},L:function(a){K.enable(a)},g:function(a){L.za[a].enabled=
!0;K.enableVertexAttribArray(a)},j:function(a,b){Mb(a,b,"createBuffer",Eb)},V:function(a,b){Mb(a,b,"createVertexArray",Fb)},h:function(a,b){return K.getAttribLocation(P[a],G(b))},_:function(a,b,c,d){a=K.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Nb(a,z,d,b):0;c&&(B[c>>2]=b)},z:function(a,b,c){if(c)if(a>=Db)R(1281);else if(a=P[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.Ha)for(b=0;b<K.getProgramParameter(a,35718);++b)a.Ha=
Math.max(a.Ha,K.getActiveUniform(a,b).name.length+1);B[c>>2]=a.Ha}else if(35722==b){if(!a.Fa)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Fa=Math.max(a.Fa,K.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.Fa}else if(35381==b){if(!a.Ga)for(b=0;b<K.getProgramParameter(a,35382);++b)a.Ga=Math.max(a.Ga,K.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.Ga}else B[c>>2]=K.getProgramParameter(a,b);else R(1281)},p:function(a,b,c,d){a=K.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?Nb(a,
z,d,b):0;c&&(B[c>>2]=b)},t:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(Q[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=K.getShaderParameter(Q[a],b):R(1281)},a:function(a,b){b=G(b);if(a=P[a]){var c=a,d=c.Ca,e=c.sb,g;if(!d)for(c.Ca=d={},c.rb={},g=0;g<K.getProgramParameter(c,35718);++g){var h=K.getActiveUniform(c,g);var m=h.name;h=h.size;var q=Ob(m);q=0<q?m.slice(0,q):m;var p=c.Va;c.Va+=h;e[q]=[h,p];for(m=0;m<h;++m)d[p]=
m,c.rb[p++]=q}c=a.Ca;d=0;e=b;g=Ob(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.sb[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},A:function(a){a=P[a];K.linkProgram(a);a.Ca=0;a.sb={}},v:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?B[d+4*g>>2]:-1;e+=G(B[c+4*g>>2],0>h?void 0:h)}K.shaderSource(Q[a],e)},e:function(a,b){K.uniform1f(Pb(a),b)},s:function(a,b,c,d){b&&K.uniformMatrix4fv(Pb(a),!!c,oa,d>>2,16*b)},l:function(a){a=P[a];K.useProgram(a);
K.yb=a},f:function(a,b,c,d,e,g){var h=L.za[a];K.Za?(h.Ma=!1,K.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.mb=d,h.Ua=e,h.ta=g,h.Ma=!0,h.tb=function(m,q,p,t,u,x){this.vertexAttribPointer(m,q,p,t,u,x)})},O:function(a,b,c,d){K.viewport(a,b,c,d)},Y:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?lb():xb(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<S[139265];e==Y.length&&
(d?f.Aa=fb(f.canvas,!0,!0,{antialias:1<S[135181],depth:0<S[135173],stencil:0<S[135174],alpha:0<S[135172]}):cb());!f.Aa&&d?g=0:(a=new Qb(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,X=a,g=a.id)}return g},Q:function(a,b,c){pa[b>>3]=N;pa[c>>3]=rb},P:function(a,b){return(a=0>=a||!Y?null:Y[a-1])?0<(a.buttons&1<<b):0},Z:function(){if(Y)return 1;Ka();S=Nc;Y=[];X=null;Mc="number"==typeof devicePixelRatio&&devicePixelRatio||1;window.addEventListener("gamepadconnected",Sc,!0);window.addEventListener("gamepaddisconnected",
Uc,!0);window.addEventListener("keydown",Vc,!0);window.addEventListener("keypress",Qc,!0);window.addEventListener("keyup",Wc,!0);window.addEventListener("blur",Xc,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Mc="number"==typeof devicePixelRatio&&devicePixelRatio||1;X&&X.ub&&O(X.ub)(X.id,Mc,Mc)})();f.canvas.addEventListener("touchmove",Yc,!0);f.canvas.addEventListener("touchstart",bd,!0);f.canvas.addEventListener("touchcancel",
cd,!0);f.canvas.addEventListener("touchend",cd,!0);f.canvas.addEventListener("mousemove",Yc,!0);f.canvas.addEventListener("mousedown",bd,!0);f.canvas.addEventListener("mouseup",cd,!0);f.canvas.addEventListener("wheel",dd,!0);f.canvas.addEventListener("mousewheel",dd,!0);f.canvas.addEventListener("mouseenter",Zc,!0);f.canvas.addEventListener("mouseleave",$c,!0);f.canvas.addEventListener("drop",hd,!0);f.canvas.addEventListener("dragover",jd,!0);wb.push((b,c)=>{if(X){var d=!0;document.fullscreen||document.fullScreen||
document.mozFullScreen||document.webkitIsFullScreen?(X.pb=X.x,X.qb=X.y,X.ob=X.width,X.nb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.Ra=!0):1==X.Ra?(X.x=X.pb,X.y=X.qb,X.width=X.ob,X.height=X.nb,X.Ra=!1):X.width!=b||X.height!=c?(X.width=b,X.height=c):d=!1;d&&(xb(X.width,X.height,!0),X&&X.vb&&O(X.vb)(X.id,X.width,X.height),X&&X.eb&&O(X.eb)(X.id,X.width,X.height))}});return 1},W:function(){},M:function(){},T:function(a,b){if(a=0>=a||!Y?null:Y[a-1]){var c=a.Ka;a.Ka=b;b=c}else b=null;
return b},N:function(){},X:function(){window.removeEventListener("gamepadconnected",Sc,!0);window.removeEventListener("gamepaddisconnected",Uc,!0);window.removeEventListener("keydown",Vc,!0);window.removeEventListener("keypress",Qc,!0);window.removeEventListener("keyup",Wc,!0);window.removeEventListener("blur",Xc,!0);f.canvas.removeEventListener("touchmove",Yc,!0);f.canvas.removeEventListener("touchstart",bd,!0);f.canvas.removeEventListener("touchcancel",cd,!0);f.canvas.removeEventListener("touchend",
cd,!0);f.canvas.removeEventListener("mousemove",Yc,!0);f.canvas.removeEventListener("mousedown",bd,!0);f.canvas.removeEventListener("mouseup",cd,!0);f.canvas.removeEventListener("wheel",dd,!0);f.canvas.removeEventListener("mousewheel",dd,!0);f.canvas.removeEventListener("mouseenter",Zc,!0);f.canvas.removeEventListener("mouseleave",$c,!0);f.canvas.removeEventListener("drop",hd,!0);f.canvas.removeEventListener("dragover",jd,!0);f.canvas.width=f.canvas.height=1;X=Y=null},n:function(a,b){S[a]=b}};
(function(){function a(c){c=c.exports;f.asm=c;la=f.asm.$;qa();ra=f.asm.ea;ta.unshift(f.asm.aa);D--;f.monitorRunDependencies&&f.monitorRunDependencies(D);if(0==D&&(null!==xa&&(clearInterval(xa),xa=null),ya)){var d=ya;ya=null;d()}return c}var b={a:kd};D++;f.monitorRunDependencies&&f.monitorRunDependencies(D);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return r("Module.instantiateWasm callback failed with error: "+c),!1}Ea(b,function(c){a(c.instance)});return{}})();
f._resizeWindow=function(){return(f._resizeWindow=f.asm.ba).apply(null,arguments)};f._updateImage=function(){return(f._updateImage=f.asm.ca).apply(null,arguments)};var ld=f._main=function(){return(ld=f._main=f.asm.da).apply(null,arguments)},Tb=f._malloc=function(){return(Tb=f._malloc=f.asm.fa).apply(null,arguments)},gd=f._free=function(){return(gd=f._free=f.asm.ga).apply(null,arguments)};function md(){return(md=f.asm.ha).apply(null,arguments)}
function nd(){return(nd=f.asm.ia).apply(null,arguments)}function od(){return(od=f.asm.ja).apply(null,arguments)}
f.ccall=function(a,b,c,d){var e={string:p=>{var t=0;if(null!==p&&void 0!==p&&0!==p){t=Rb(p)+1;var u=od(t);Nb(p,z,u,t);t=u}return t},array:p=>{var t=od(p.length);y.set(p,t);return t}};a=f["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var q=e[c[m]];q?(0===h&&(h=md()),g[m]=q(d[m])):g[m]=d[m]}c=a.apply(null,g);return c=function(p){0!==h&&nd(h);return"string"===b?G(p):"boolean"===b?!!p:p}(c)};var pd;ya=function qd(){pd||sd();pd||(ya=qd)};
function sd(){function a(){if(!pd&&(pd=!0,f.calledRun=!0,!w)){f.noFSInit||Ic||(Ic=!0,Hc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Lc("stdin",f.stdin):Dc("/dev/tty","/dev/stdin"),f.stdout?Lc("stdout",null,f.stdout):Dc("/dev/tty","/dev/stdout"),f.stderr?Lc("stderr",null,f.stderr):Dc("/dev/tty1","/dev/stderr"),Fc("/dev/stdin",0),Fc("/dev/stdout",1),Fc("/dev/stderr",1));qc=!1;Fa(ta);Fa(ua);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(td){var b=ld;try{var c=b(0,0);ma=c;Ma(c)}catch(d){La(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),va.unshift(b);Fa(va)}}if(!(0<D)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Fa(sa);0<D||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var td=!0;f.noInitialRun&&(td=!1);sd();
