var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");m=l?ja.dirname(m)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!f.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ka||a.context instanceof ka))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ca=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):"",
fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var r=f.print||console.log.bind(console),u=f.printErr||console.error.bind(console);
Object.assign(f,aa);aa=null;f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var la;f.wasmBinary&&(la=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&x("no native wasm support detected");var ma,y=!1,na,B,C,oa,pa,D,E,qa,ra;
function sa(){var a=ma.buffer;f.HEAP8=B=new Int8Array(a);f.HEAP16=oa=new Int16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=pa=new Uint16Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=qa=new Float32Array(a);f.HEAPF64=ra=new Float64Array(a)}var ta,ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var F=0,za=null,Aa=null;
function x(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";u(a);y=!0;na=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="module.wasm";if(!Ba(G)){var Ca=G;G=f.locateFile?f.locateFile(Ca,m):m+Ca}function Da(a){try{if(a==G&&la)return new Uint8Array(la);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Ea(a){if(!la&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Da(a));if(ha)return new Promise((b,c)=>{ha(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Da(a))}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{u("failed to asynchronously prepare wasm: "+d);x(d)})}
function Ga(a,b){var c=G;la||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){u("wasm streaming compile failed: "+e);u("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ha(a){for(;0<a.length;)a.shift()(f)}f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return B[a>>0];case "i8":return B[a>>0];case "i16":return oa[a>>1];case "i32":return D[a>>2];case "i64":return D[a>>2];case "float":return qa[a>>2];case "double":return ra[a>>3];case "*":return E[a>>2];default:x(`invalid type for getValue: ${b}`)}};var Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function I(a,b){return a?H(C,a,b):""}
function Ja(a){this.Ia=a-24;this.Rb=function(b){E[this.Ia+4>>2]=b};this.Qb=function(b){E[this.Ia+8>>2]=b};this.Ga=function(b,c){this.lc();this.Rb(b);this.Qb(c)};this.lc=function(){E[this.Ia+16>>2]=0}}var Ka=0,La=0,Ma;Ma=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function Na(a){a instanceof ka||"unwind"==a||ca(1,a)}function Oa(a){na=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);y=!0}ca(a,new ka(a))}
function Pa(a){if(!y)try{if(a(),!noExitRuntime)try{na=a=na,Oa(a)}catch(b){Na(b)}}catch(b){Na(b)}}function Qa(a){setTimeout(()=>{Pa(a)},1E4)}var Ra=f.preloadPlugins||[],Sa=!1,J=null,K=0,Ta=null,Ua=0,Va=0,Wa=0,Xa=0,Ya=[],Za={},$a,ab,bb,cb=!1,db=!1,eb=[];
function fb(){function a(){db=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!gb){gb=!0;Ra.push({canHandle:function(c){return!f.Dc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=new Blob([c],{type:hb(d)});k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:hb(d)}));var p=URL.createObjectURL(k),q=new Image;q.onload=()=>{q.complete||x("Image "+
d+" could not be decoded");var n=document.createElement("canvas");n.width=q.width;n.height=q.height;n.getContext("2d").drawImage(q,0,0);URL.revokeObjectURL(p);e&&e(c)};q.onerror=()=>{r("Image "+p+" could not be decoded");g&&g()};q.src=p}});Ra.push({canHandle:function(c){return!f.Cc&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){k||(k=!0,e&&e(c))}var k=!1,p=URL.createObjectURL(new Blob([c],{type:hb(d)})),q=new Audio;q.addEventListener("canplaythrough",()=>g(q),!1);
q.onerror=function(){if(!k){u("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var n="",t=0,v=0,A=0;A<c.length;A++)for(t=t<<8|c[A],v+=8;6<=v;){var h=t>>v-6&63;v-=6;n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[h]}2==v?(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],n+="=="):4==v&&(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],n+="=");q.src="data:audio/x-"+d.substr(-3)+
";base64,"+n;g(q)}};q.src=p;Qa(()=>{g(q)})}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!db&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ib(a,b,c,d){if(b&&f.Ra&&a==f.canvas)return f.Ra;var e;if(b){var g={antialias:!1,alpha:!1,$b:2};if(d)for(var k in d)g[k]=d[k];if("undefined"!=typeof jb&&(e=kb(a,g)))var p=lb[e].Ua}else p=a.getContext("2d");if(!p)return null;c&&(b||"undefined"==typeof L||x("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Ra=p,b&&(M=lb[e],f.Ra=L=M&&M.Ua),f.Gc=b,eb.forEach(q=>q()),fb());return p}var mb=!1,nb=void 0,ob=void 0;
function pb(a,b){function c(){cb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=qb,nb&&d.requestPointerLock(),cb=!0,ob?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=E[SDL.screen>>2]|8388608),rb(f.canvas),sb()):rb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),ob?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=E[SDL.screen>>2]&
-8388609),rb(f.canvas),sb()):rb(d));if(f.onFullScreen)f.onFullScreen(cb);if(f.onFullscreen)f.onFullscreen(cb)}nb=a;ob=b;"undefined"==typeof nb&&(nb=!0);"undefined"==typeof ob&&(ob=!1);var d=f.canvas;mb||(mb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function qb(){if(!cb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var tb=0;function ub(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===tb)tb=b+1E3/60;else for(;b+2>=tb;)tb+=1E3/60;setTimeout(a,Math.max(tb-b,0))}}
function hb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var vb=0,wb=0,xb=0,yb=0;
function zb(a){if(db)"mousemove"!=a.type&&"mozMovementX"in a?xb=yb=0:(xb=a.movementX||a.mozMovementX||a.webkitMovementX||0,yb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(vb=SDL.zc+xb,wb=SDL.Ac+yb):(vb+=xb,wb+=yb);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,xb=e-vb,yb=a-wb,vb=e,wb=a)}}var Ab=[];function sb(){var a=f.canvas;Ab.forEach(b=>b(a.width,a.height))}function Bb(a,b,c){rb(f.canvas,a,b);c||sb()}
function rb(a,b,c){b&&c?(a.kc=b,a.Yb=c):(b=a.kc,c=a.Yb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}ob?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var gb;
function Cb(a,b){Va=a;Wa=b;if(Ta)if(Sa||(Sa=!0),0==a)J=function(){var d=Math.max(0,ab+b-Ma())|0;setTimeout(bb,d)};else if(1==a)J=function(){ub(bb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);l?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}J=function(){setImmediate(bb)}}}
function Db(a,b,c,d,e){!Ta||x("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ta=a;Ua=d;var g=K;Sa=!1;bb=function(){if(!y)if(0<Ya.length){var k=Date.now(),p=Ya.shift();p.vc(p.oc);if($a){var q=$a,n=0==q%1?q-1:Math.floor(q);$a=p.rc?n:(8*q+(n+.5))/9}r('main loop blocker "'+p.name+'" took '+(Date.now()-k)+" ms");f.setStatus&&(k=f.statusMessage||"Please wait...",
p=$a,q=Za.uc,p?p<q?f.setStatus(k+" ("+(q-p)+"/"+q+")"):f.setStatus(k):f.setStatus(""));g<K||setTimeout(bb,0)}else if(!(g<K))if(Xa=Xa+1|0,1==Va&&1<Wa&&0!=Xa%Wa)J();else{0==Va&&(ab=Ma());if(M)for(k=M.Pa,M.Pa=M.Sa,M.Sa=k,k=M.Ja,M.Ja=M.bb,M.bb=k,k=Eb(2097152),p=0;p<=k;++p)M.Ja[p]=0;y||f.preMainLoop&&!1===f.preMainLoop()||(Pa(a),f.postMainLoop&&f.postMainLoop());g<K||("object"==typeof SDL&&SDL.audio&&SDL.audio.cc&&SDL.audio.cc(),J())}};e||(b&&0<b?Cb(0,1E3/b):Cb(1,1),J());if(c)throw"unwind";}var Fb=[];
function N(a){var b=Fb[a];b||(a>=Fb.length&&(Fb.length=a+1),Fb[a]=b=ta.get(a));return b}var Gb={};function Hb(){if(!Ib){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Gb)void 0===Gb[b]?delete a[b]:a[b]=Gb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ib=c}return Ib}
var Ib,Jb=[null,[],[]],Kb=1,Lb=[],O=[],Mb=[],P=[],Nb=[],lb=[],Ob=[1,1,2,2,4,4,4,2,3,4,8];function Q(a){Pb||(Pb=a)}function Qb(a){for(var b=Kb++,c=a.length;c<b;c++)a[c]=null;return b}function Eb(a){return 32-Math.clz32(0===a?0:a-1)}function kb(a,b){a.Ga||(a.Ga=a.getContext,a.getContext=function(d,e){e=a.Ga(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Rb(c,b):0}
function Rb(a,b){var c=Qb(lb),d={xc:c,attributes:b,version:b.$b,Ua:a};a.canvas&&(a.canvas.mc=d);lb[c]=d;("undefined"==typeof b.Wb||b.Wb)&&Sb(d);d.Bb=d.Ua.getParameter(34921);d.Qa=[];for(a=0;a<d.Bb;a++)d.Qa[a]={enabled:!1,fb:!1,size:0,type:0,Gb:0,nb:0,Ia:0,Nb:null};a=Eb(2097152);d.Ja=[];d.bb=[];d.Ja.length=d.bb.length=a+1;d.Pa=[];d.Sa=[];d.Pa.length=d.Sa.length=a+1;d.Oa=[];d.Oa.length=a+1;for(b=0;b<=a;++b){d.Oa[b]=null;d.Ja[b]=d.bb[b]=0;d.Pa[b]=[];d.Sa[b]=[];var e=d.Pa[b],g=d.Sa[b];e.length=g.length=
64;for(var k=0;64>k;++k)e[k]=g[k]=null}return c}
function Sb(a){a||(a=M);if(!a.Zb){a.Zb=!0;var b=a.Ua;b.tc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.yc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.ub=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.ub)b.ub=b.getExtension("EXT_disjoint_timer_query");b.Bc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var jb={},Pb,M,Tb;function Ub(a,b,c,d){for(var e=0;e<a;e++){var g=L[c](),k=g&&Qb(d);g?(g.name=k,d[k]=g):Q(1282);D[b+4*e>>2]=k}}
function Vb(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}function Wb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Xb(a){var b=L.Vb;if(b){var c=b.Ta[a];"number"==typeof c&&(b.Ta[a]=c=L.getUniformLocation(b,b.Lb[a]+(0<c?"["+c+"]":"")));return c}Q(1282)}function Yb(a,b,c,d){this.id=a;this.y=this.x=0;this.kb=!1;this.Kb=this.Jb=0;this.width=b;this.height=c;this.Ib=b;this.Hb=c;this.title=d;this.attributes=R;this.buttons=0;this.keys=[];this.ib=[];this.rb=this.Ab=this.jb=this.ab=this.Va=this.hb=this.Eb=this.Ob=this.yb=this.Pb=this.title=null}
function Zb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function $b(a){var b=Zb(a)+1,c=ac(b);c&&Vb(a,C,c,b);return c}function bc(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ea)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}x("initRandomDevice")}
function cc(a){return(cc=bc())(a)}
var dc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ec=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=dc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},fc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},gc=a=>
{if("/"===a)return"/";a=ec(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function hc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=dc(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function ic(a,b){var c=Array(Zb(a)+1);a=Vb(a,c,0,c.length);b&&(c.length=a);return c}var jc=[];
function kc(a,b){jc[a]={input:[],output:[],Na:b};lc(a,mc)}
var mc={open:function(a){var b=jc[a.node.rdev];if(!b)throw new S(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Na.fsync(a.tty)},fsync:function(a){a.tty.Na.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Na.zb)throw new S(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Na.zb(a.tty)}catch(p){throw new S(29);}if(void 0===k&&0===e)throw new S(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Na.lb)throw new S(60);
try{for(var e=0;e<d;e++)a.tty.Na.lb(a.tty,b[c+e])}catch(g){throw new S(29);}d&&(a.node.timestamp=Date.now());return e}},nc={zb:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ic(b,!0)}return a.input.shift()},lb:function(a,b){null===b||10===b?(r(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(r(H(a.output,0)),a.output=[])}},oc={lb:function(a,b){null===b||10===b?(u(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(u(H(a.output,0)),a.output=[])}},T={Ca:null,Fa:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.Ca||(T.Ca={dir:{node:{Ha:T.za.Ha,Da:T.za.Da,lookup:T.za.lookup,Za:T.za.Za,rename:T.za.rename,unlink:T.za.unlink,rmdir:T.za.rmdir,readdir:T.za.readdir,symlink:T.za.symlink},stream:{Ka:T.Aa.Ka}},file:{node:{Ha:T.za.Ha,Da:T.za.Da},stream:{Ka:T.Aa.Ka,read:T.Aa.read,write:T.Aa.write,qb:T.Aa.qb,Cb:T.Aa.Cb,Fb:T.Aa.Fb}},link:{node:{Ha:T.za.Ha,Da:T.za.Da,readlink:T.za.readlink},stream:{}},sb:{node:{Ha:T.za.Ha,Da:T.za.Da},stream:pc}});c=qc(a,b,
c,d);16384===(c.mode&61440)?(c.za=T.Ca.dir.node,c.Aa=T.Ca.dir.stream,c.ya={}):32768===(c.mode&61440)?(c.za=T.Ca.file.node,c.Aa=T.Ca.file.stream,c.Ba=0,c.ya=null):40960===(c.mode&61440)?(c.za=T.Ca.link.node,c.Aa=T.Ca.link.stream):8192===(c.mode&61440)&&(c.za=T.Ca.sb.node,c.Aa=T.Ca.sb.stream);c.timestamp=Date.now();a&&(a.ya[b]=c,a.timestamp=c.timestamp);return c},wc:function(a){return a.ya?a.ya.subarray?a.ya.subarray(0,a.Ba):new Uint8Array(a.ya):new Uint8Array(0)},vb:function(a,b){var c=a.ya?a.ya.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ya,a.ya=new Uint8Array(b),0<a.Ba&&a.ya.set(c.subarray(0,a.Ba),0))},dc:function(a,b){if(a.Ba!=b)if(0==b)a.ya=null,a.Ba=0;else{var c=a.ya;a.ya=new Uint8Array(b);c&&a.ya.set(c.subarray(0,Math.min(b,a.Ba)));a.Ba=b}},za:{Ha:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ba:40960===(a.mode&
61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Sb=4096;b.blocks=Math.ceil(b.size/b.Sb);return b},Da:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.dc(a,b.size)},lookup:function(){throw rc[44];},Za:function(a,b,c,d){return T.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=sc(b,c)}catch(g){}if(d)for(var e in d.ya)throw new S(55);
}delete a.parent.ya[a.name];a.parent.timestamp=Date.now();a.name=c;b.ya[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ya[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=sc(a,b),d;for(d in c.ya)throw new S(55);delete a.ya[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ya)a.ya.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new S(28);
return a.link}},Aa:{read:function(a,b,c,d,e){var g=a.node.ya;if(e>=a.node.Ba)return 0;a=Math.min(a.node.Ba-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===B.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ya||a.ya.subarray)){if(g)return a.ya=b.subarray(c,c+d),a.Ba=d;if(0===a.Ba&&0===e)return a.ya=b.slice(c,c+d),a.Ba=d;if(e+d<=a.Ba)return a.ya.set(b.subarray(c,c+d),e),d}T.vb(a,e+
d);if(a.ya.subarray&&b.subarray)a.ya.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ya[e+g]=b[c+g];a.Ba=Math.max(a.Ba,e+d);return d},Ka:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ba);if(0>b)throw new S(28);return b},qb:function(a,b,c){T.vb(a.node,b+c);a.node.Ba=Math.max(a.node.Ba,b+c)},Cb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.ya;if(e&2||a.buffer!==B.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);c=!0;x();b=void 0;if(!b)throw new S(48);B.set(a,b)}else c=!1,b=a.byteOffset;return{Ia:b,nc:c}},Fb:function(a,b,c,d){T.Aa.write(a,b,0,d,c,!1);return 0}}};function tc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var uc=null,vc={},wc=[],xc=1,yc=null,zc=!0,S=null,rc={},V=(a,b={})=>{a=hc(a);if(!a)return{path:"",node:null};b=Object.assign({xb:!0,mb:0},b);if(8<b.mb)throw new S(32);a=a.split("/").filter(k=>!!k);for(var c=uc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=sc(c,a[e]);d=ec(d+"/"+a[e]);c.$a&&(!g||g&&b.xb)&&(c=c.$a.root);if(!g||b.wb)for(g=0;40960===(c.mode&61440);)if(c=Ac(d),d=hc(fc(d),c),c=V(d,{mb:b.mb+1}).node,40<g++)throw new S(32);}return{path:d,node:c}},Bc=a=>{for(var b;;){if(a===
a.parent)return a=a.Fa.Db,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},Cc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yc.length},sc=(a,b)=>{var c;if(c=(c=Dc(a,"x"))?c:a.za.lookup?0:2)throw new S(c,a);for(c=yc[Cc(a.id,b)];c;c=c.bc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.za.lookup(a,b)},qc=(a,b,c,d)=>{a=new Ec(a,b,c,d);b=Cc(a.parent.id,a.name);a.bc=yc[b];return yc[b]=a},Fc=a=>{var b=["r","w","rw"][a&3];
a&512&&(b+="w");return b},Dc=(a,b)=>{if(zc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Gc=(a,b)=>{try{return sc(a,b),20}catch(c){}return Dc(a,"wx")},Hc=()=>{for(var a=0;4096>=a;a++)if(!wc[a])return a;throw new S(33);},Jc=a=>{Ic||(Ic=function(){this.Ga={}},Ic.prototype={},Object.defineProperties(Ic.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.Ga.flags},
set:function(c){this.Ga.flags=c}},position:{get:function(){return this.Ga.position},set:function(c){this.Ga.position=c}}}));a=Object.assign(new Ic,a);var b=Hc();a.fd=b;return wc[b]=a},pc={open:a=>{a.Aa=vc[a.node.rdev].Aa;a.Aa.open&&a.Aa.open(a)},Ka:()=>{throw new S(70);}},lc=(a,b)=>{vc[a]={Aa:b}},Kc=(a,b)=>{var c="/"===b,d=!b;if(c&&uc)throw new S(10);if(!c&&!d){var e=V(b,{xb:!1});b=e.path;e=e.node;if(e.$a)throw new S(10);if(16384!==(e.mode&61440))throw new S(54);}b={type:a,Ec:{},Db:b,ac:[]};a=a.Fa(b);
a.Fa=b;b.root=a;c?uc=a:e&&(e.$a=b,e.Fa&&e.Fa.ac.push(b))},W=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=gc(a);if(!a||"."===a||".."===a)throw new S(28);var e=Gc(d,a);if(e)throw new S(e);if(!d.za.Za)throw new S(63);return d.za.Za(d,a,b,c)},Lc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},Mc=(a,b)=>{if(!hc(a))throw new S(44);var c=V(b,{parent:!0}).node;if(!c)throw new S(44);b=gc(b);var d=Gc(c,b);if(d)throw new S(d);if(!c.za.symlink)throw new S(63);c.za.symlink(c,b,a)},Ac=a=>{a=V(a).node;if(!a)throw new S(44);
if(!a.za.readlink)throw new S(28);return hc(Bc(a.parent),a.za.readlink(a))},Oc=(a,b,c)=>{if(""===a)throw new S(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=ec(a);try{e=V(a,{wb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new S(20);}else e=W(a,c,0),d=!0;if(!e)throw new S(44);8192===(e.mode&
61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new S(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Fc(b)||b&512)?31:Dc(e,Fc(b)):44))throw new S(c);if(b&512&&!d){c=e;c="string"==typeof c?V(c,{wb:!0}).node:c;if(!c.za.Da)throw new S(63);if(16384===(c.mode&61440))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(d=Dc(c,"w"))throw new S(d);c.za.Da(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Jc({node:e,path:Bc(e),flags:b,seekable:!0,position:0,Aa:e.Aa,
jc:[],error:!1});e.Aa.open&&e.Aa.open(e);!f.logReadFiles||b&1||(Nc||(Nc={}),a in Nc||(Nc[a]=1));return e},Pc=(a,b,c,d)=>{var e=void 0;if(0>c||0>e)throw new S(28);if(null===a.fd)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(16384===(a.node.mode&61440))throw new S(31);if(!a.Aa.write)throw new S(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new S(8);if(!a.seekable||!a.Aa.Ka)throw new S(70);a.position=a.Aa.Ka(a,0,2);a.jc=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S(70);
b=a.Aa.write(a,b,0,c,e,d);g||(a.position+=b)},Qc=()=>{S||(S=function(a,b){this.name="ErrnoError";this.node=b;this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(a=>{rc[a]=new S(a);rc[a].stack="<generic error, no stack>"}))},Rc,Sc=()=>{var a="/";a="string"==typeof a?a:Bc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=ec(a+"/"+c);try{W(a,16895,0)}catch(d){}}}},Vc=(a,b,c)=>{a=ec("/dev/"+a);var d=tc(!!b,!!c);Tc||(Tc=64);var e=Tc++<<8|0;
lc(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,k,p,q)=>{for(var n=0,t=0;t<q;t++){try{var v=b()}catch(A){throw new S(29);}if(void 0===v&&0===n)throw new S(6);if(null===v||void 0===v)break;n++;k[p+t]=v}n&&(g.node.timestamp=Date.now());return n},write:(g,k,p,q)=>{for(var n=0;n<q;n++)try{c(k[p+n])}catch(t){throw new S(29);}q&&(g.node.timestamp=Date.now());return n}});Lc(a,d,e)},Tc,Ic,Nc,X=null,Wc=null,Y=null,R=null,Xc={131073:0,131074:0,131075:1,131076:1,131077:1,
131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Yc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Zc(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function $c(a){X&&X.rb&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||N(X.rb)(X.id,a))}function ad(a,b){if(X){var c=Yc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.ib[a]=b;X.Ab&&(d&&(b=2),N(X.Ab)(X.id,c,a,b,Zc()))}}}
function bd(){cd()}function dd(){cd()}function ed(a){ad(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function fd(a){ad(a.keyCode,0)}function gd(){if(X)for(var a=0;a<X.ib.length;++a)X.ib[a]&&ad(a,0)}function hd(a){X&&(zb(a),a.target==f.canvas&&X.hb&&X.hb&&N(X.hb)(X.id,vb,wb))}function jd(a){X&&a.target==f.canvas&&X.Va&&N(X.Va)(X.id,1)}function kd(a){X&&a.target==f.canvas&&X.Va&&N(X.Va)(X.id,0)}
function ld(a,b){if(X&&(zb(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.Eb&&N(X.Eb)(X.id,c,b,Zc())}}function md(a){X&&ld(a,1)}function nd(a){X&&ld(a,0)}
function od(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.ab&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;N(X.ab)(X.id,b,c);a.preventDefault()}}
var Z={},pd=[],qd=null;
function cd(){if(Xa!==qd||!Xa){pd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];qd=Xa;for(var a=0;a<pd.length;++a){var b=pd[a];if(b){Z[a]||(r("glfw joystick connected:",a),Z[a]={id:$b(b.id),qc:b.buttons.length,pc:b.axes.length,buttons:ac(b.buttons.length),axes:ac(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)B[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)qa[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(r("glfw joystick disconnected",
a),rd(Z[a].id),rd(Z[a].buttons),rd(Z[a].axes),delete Z[a])}}}
function sd(a){function b(p){var q="/.glfw_dropped_files/"+p.name.replace(/\//g,"_"),n=new FileReader;n.onloadend=v=>{if(2!=n.readyState)++g,r("failed to read dropped file: "+p.name+": "+n.error);else{var A=new Uint8Array(v.target.result);v={};v.flags=v.flags||577;var h=Oc(q,v.flags,v.mode);if("string"==typeof A){var w=new Uint8Array(Zb(A)+1);A=Vb(A,w,0,w.length);Pc(h,w,A,v.Tb)}else if(ArrayBuffer.isView(A))Pc(h,A,A.byteLength,v.Tb);else throw Error("Unsupported data type");if(null===h.fd)throw new S(8);
h.Xb&&(h.Xb=null);try{h.Aa.close&&h.Aa.close(h)}catch(z){throw z;}finally{wc[h.fd]=null}h.fd=null;if(++g===e){N(X.jb)(X.id,e,c);for(v=0;v<d.length;++v)rd(d[v]);rd(c)}}};n.readAsArrayBuffer(p);var t=$b(q);d.push(t);E[c+4*k>>2]=t}if(X&&X.jb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=ac(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Sc();for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}
function td(a){if(X&&X.jb)return a.preventDefault(),!1}function ud(a){return 0===a%4&&(0!==a%100||0===a%400)}var vd=[31,29,31,30,31,30,31,31,30,31,30,31],wd=[31,28,31,30,31,30,31,31,30,31,30,31];
function xd(a,b,c,d){function e(h,w,z){for(h="number"==typeof h?h.toString():h||"";h.length<w;)h=z[0]+h;return h}function g(h,w){return e(h,w,"0")}function k(h,w){function z(Uc){return 0>Uc?-1:0<Uc?1:0}var U;0===(U=z(h.getFullYear()-w.getFullYear()))&&0===(U=z(h.getMonth()-w.getMonth()))&&(U=z(h.getDate()-w.getDate()));return U}function p(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){var w=h.La;for(h=new Date((new Date(h.Ma+1900,0,1)).getTime());0<w;){var z=h.getMonth(),U=(ud(h.getFullYear())?vd:wd)[z];if(w>U-h.getDate())w-=U-h.getDate()+1,h.setDate(1),11>z?h.setMonth(z+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+w);break}}z=new Date(h.getFullYear()+1,0,4);w=p(new Date(h.getFullYear(),
0,4));z=p(z);return 0>=k(w,h)?0>=k(z,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=D[d+40>>2];d={hc:D[d>>2],fc:D[d+4>>2],cb:D[d+8>>2],ob:D[d+12>>2],eb:D[d+16>>2],Ma:D[d+20>>2],Ea:D[d+24>>2],La:D[d+28>>2],Fc:D[d+32>>2],ec:D[d+36>>2],ic:n?I(n):""};c=I(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in n)c=c.replace(new RegExp(t,"g"),n[t]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");n={"%a":function(h){return v[h.Ea].substring(0,3)},"%A":function(h){return v[h.Ea]},"%b":function(h){return A[h.eb].substring(0,3)},"%B":function(h){return A[h.eb]},
"%C":function(h){return g((h.Ma+1900)/100|0,2)},"%d":function(h){return g(h.ob,2)},"%e":function(h){return e(h.ob,2," ")},"%g":function(h){return q(h).toString().substring(2)},"%G":function(h){return q(h)},"%H":function(h){return g(h.cb,2)},"%I":function(h){h=h.cb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){for(var w=0,z=0;z<=h.eb-1;w+=(ud(h.Ma+1900)?vd:wd)[z++]);return g(h.ob+w,3)},"%m":function(h){return g(h.eb+1,2)},"%M":function(h){return g(h.fc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=
h.cb&&12>h.cb?"AM":"PM"},"%S":function(h){return g(h.hc,2)},"%t":function(){return"\t"},"%u":function(h){return h.Ea||7},"%U":function(h){return g(Math.floor((h.La+7-h.Ea)/7),2)},"%V":function(h){var w=Math.floor((h.La+7-(h.Ea+6)%7)/7);2>=(h.Ea+371-h.La-2)%7&&w++;if(w)53==w&&(z=(h.Ea+371-h.La)%7,4==z||3==z&&ud(h.Ma)||(w=1));else{w=52;var z=(h.Ea+7-h.La-1)%7;(4==z||5==z&&ud(h.Ma%400-1))&&w++}return g(w,2)},"%w":function(h){return h.Ea},"%W":function(h){return g(Math.floor((h.La+7-(h.Ea+6)%7)/7),2)},
"%y":function(h){return(h.Ma+1900).toString().substring(2)},"%Y":function(h){return h.Ma+1900},"%z":function(h){h=h.ec;var w=0<=h;h=Math.abs(h)/60;return(w?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.ic},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(t in n)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),n[t](d)));c=c.replace(/\0\0/g,"%");t=ic(c,!1);if(t.length>b)return 0;B.set(t,a);return t.length-1}f.requestFullscreen=function(a,b){pb(a,b)};
f.requestAnimationFrame=function(a){ub(a)};f.setCanvasSize=function(a,b,c){Bb(a,b,c)};f.pauseMainLoop=function(){J=null;K++};f.resumeMainLoop=function(){K++;var a=Va,b=Wa,c=Ta;Ta=null;Db(c,0,!1,Ua,!0);Cb(a,b);J()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return ib(a,b,c,d)};var L;
function Ec(a,b,c,d){a||(a=this);this.parent=a;this.Fa=a.Fa;this.$a=null;this.id=xc++;this.name=b;this.mode=c;this.za={};this.Aa={};this.rdev=d}Object.defineProperties(Ec.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Qc();yc=Array(4096);Kc(T,"/");W("/tmp",16895,0);W("/home",16895,0);W("/home/web_user",16895,0);
(()=>{W("/dev",16895,0);lc(259,{read:()=>0,write:(d,e,g,k)=>k});Lc("/dev/null",259);kc(1280,nc);kc(1536,oc);Lc("/dev/tty",1280);Lc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=cc(a).byteLength);return a[--b]};Vc("random",c);Vc("urandom",c);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();
(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);Kc({Fa:()=>{var b=qc(a,"fd",16895,73);b.za={lookup:(c,d)=>{var e=wc[+d];if(!e)throw new S(8);c={parent:null,Fa:{Db:"fake"},za:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var yd={c:function(a,b,c,d){x(`Assertion failed: ${I(a)}, at: `+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},m:function(a,b,c){(new Ja(a)).Ga(b,c);Ka=a;La++;throw Ka;},J:function(){return!0},j:function(){x("")},L:Ma,N:function(a,b,c){C.copyWithin(a,b,b+c)},K:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var k=ma.buffer;try{ma.grow(g.call(e,2147483648,
d)-k.byteLength+65535>>>16);sa();var p=1;break a}catch(q){}p=void 0}if(p)return!0}return!1},v:function(a){eval(I(a))},Z:function(a,b,c){a=N(a);Db(a,b,c)},H:function(a,b){var c=0;Hb().forEach(function(d,e){var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)B[e++>>0]=d.charCodeAt(g);B[e>>0]=0;c+=d.length+1});return 0},I:function(a,b){var c=Hb();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},M:function(){return 52},E:function(){return 70},p:function(a,b,c,d){for(var e=
0,g=0;g<c;g++){var k=E[b>>2],p=E[b+4>>2];b+=8;for(var q=0;q<p;q++){var n=C[k+q],t=Jb[a];0===n||10===n?((1===a?r:u)(H(t,0)),t.length=0):t.push(n)}e+=p}E[d>>2]=e;return 0},P:function(a){L.activeTexture(a)},o:function(a,b){L.attachShader(O[a],P[b])},b:function(a,b){34962==a?L.tb=b:34963==a&&(L.gb=b);35051==a?L.sc=b:35052==a&&(L.Ub=b);L.bindBuffer(a,Lb[b])},y:function(a,b){L.bindTexture(a,Mb[b])},$:function(a){L.bindVertexArray(Nb[a]);a=L.getParameter(34965);L.gb=a?a.name|0:0},a:function(a,b,c,d){c&&
b?L.bufferData(a,C,d,c,b):L.bufferData(a,b,d)},Q:function(a){L.clear(a)},R:function(a,b,c,d){L.clearColor(a,b,c,d)},u:function(a){L.compileShader(P[a])},F:function(){var a=Qb(O),b=L.createProgram();b.name=a;b.Ya=b.Wa=b.Xa=0;b.pb=1;O[a]=b;return a},B:function(a){var b=Qb(P);P[b]=L.createShader(a);return b},z:function(a){if(a){var b=P[a];b?(L.deleteShader(b),P[a]=null):Q(1281)}},S:function(a){L.depthFunc(a)},A:function(a,b){L.detachShader(O[a],P[b])},d:function(a){M.Qa[a].enabled=!1;L.disableVertexAttribArray(a)},
r:function(a,b,c,d){if(!L.gb){var e=1*Ob[c-5120]*b;var g=Eb(e);var k=M.Oa[g];k?g=k:(k=L.getParameter(34965),M.Oa[g]=L.createBuffer(),L.bindBuffer(34963,M.Oa[g]),L.bufferData(34963,1<<g,35048),L.bindBuffer(34963,k),g=M.Oa[g]);L.bindBuffer(34963,g);L.bufferSubData(34963,0,C.subarray(d,d+e));d=0}Tb=!1;for(e=0;e<M.Bb;++e)if(g=M.Qa[e],g.fb&&g.enabled){Tb=!0;k=g.nb;k=0<k?b*k:g.size*Ob[g.type-5120]*b;var p=Eb(k);var q=M.Pa[p],n=M.Ja[p];M.Ja[p]=M.Ja[p]+1&63;var t=q[n];t?p=t:(t=L.getParameter(34964),q[n]=
L.createBuffer(),L.bindBuffer(34962,q[n]),L.bufferData(34962,1<<p,35048),L.bindBuffer(34962,t),p=q[n]);L.bindBuffer(34962,p);L.bufferSubData(34962,0,C.subarray(g.Ia,g.Ia+k));g.Nb.call(L,e,g.size,g.type,g.Gb,g.nb,0)}L.drawElements(a,b,c,d);Tb&&L.bindBuffer(34962,Lb[L.tb]);L.gb||L.bindBuffer(34963,null)},T:function(a){L.enable(a)},f:function(a){M.Qa[a].enabled=!0;L.enableVertexAttribArray(a)},h:function(a,b){Ub(a,b,"createBuffer",Lb)},fa:function(a,b){Ub(a,b,"createTexture",Mb)},aa:function(a,b){Ub(a,
b,"createVertexArray",Nb)},g:function(a,b){return L.getAttribLocation(O[a],I(b))},ga:function(a,b,c,d){a=L.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?Vb(a,C,d,b):0;c&&(D[c>>2]=b)},C:function(a,b,c){if(c)if(a>=Kb)Q(1281);else if(a=O[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.Ya)for(b=0;b<L.getProgramParameter(a,35718);++b)a.Ya=Math.max(a.Ya,L.getActiveUniform(a,b).name.length+1);D[c>>2]=a.Ya}else if(35722==b){if(!a.Wa)for(b=
0;b<L.getProgramParameter(a,35721);++b)a.Wa=Math.max(a.Wa,L.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.Wa}else if(35381==b){if(!a.Xa)for(b=0;b<L.getProgramParameter(a,35382);++b)a.Xa=Math.max(a.Xa,L.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.Xa}else D[c>>2]=L.getProgramParameter(a,b);else Q(1281)},q:function(a,b,c,d){a=L.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Vb(a,C,d,b):0;c&&(D[c>>2]=b)},t:function(a,b,c){c?35716==b?(a=L.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),
D[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(P[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=L.getShaderParameter(P[a],b):Q(1281)},k:function(a,b){b=I(b);if(a=O[a]){var c=a,d=c.Ta,e=c.Mb,g;if(!d)for(c.Ta=d={},c.Lb={},g=0;g<L.getProgramParameter(c,35718);++g){var k=L.getActiveUniform(c,g);var p=k.name;k=k.size;var q=Wb(p);q=0<q?p.slice(0,q):p;var n=c.pb;c.pb+=k;e[q]=[k,n];for(p=0;p<k;++p)d[n]=p,c.Lb[n++]=q}c=a.Ta;d=0;e=b;g=Wb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Mb[e])&&d<e[0]&&
(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else Q(1281);return-1},D:function(a){a=O[a];L.linkProgram(a);a.Ta=0;a.Mb={}},w:function(a,b,c,d){for(var e="",g=0;g<b;++g){var k=d?D[d+4*g>>2]:-1;e+=I(D[c+4*g>>2],0>k?void 0:k)}L.shaderSource(P[a],e)},x:function(a,b,c,d,e,g,k,p,q){if(L.Ub)L.texImage2D(a,b,c,d,e,g,k,p,q);else if(q){var n=p-5120;n=0==n?B:1==n?C:2==n?oa:4==n?D:6==n?qa:5==n||28922==n||28520==n||30779==n||30782==n?E:pa;L.texImage2D(a,b,c,d,e,g,k,p,n,q>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else L.texImage2D(a,
b,c,d,e,g,k,p,null)},i:function(a,b,c){L.texParameteri(a,b,c)},O:function(a,b){L.uniform1i(Xb(a),b)},s:function(a,b,c,d){b&&L.uniformMatrix4fv(Xb(a),!!c,qa,d>>2,16*b)},l:function(a){a=O[a];L.useProgram(a);L.Vb=a},e:function(a,b,c,d,e,g){var k=M.Qa[a];L.tb?(k.fb=!1,L.vertexAttribPointer(a,b,c,!!d,e,g)):(k.size=b,k.type=c,k.Gb=d,k.nb=e,k.Ia=g,k.fb=!0,k.Nb=function(p,q,n,t,v,A){this.vertexAttribPointer(p,q,n,t,v,A)})},W:function(a,b,c,d){L.viewport(a,b,c,d)},da:function(a,b,c,d){var e;for(e=0;e<Y.length&&
null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?pb():Bb(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<R[139265];e==Y.length&&(d?f.Ra=ib(f.canvas,!0,!0,{antialias:1<R[135181],depth:0<R[135173],stencil:0<R[135174],alpha:0<R[135172]}):fb());!f.Ra&&d?g=0:(a=new Yb(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,X=a,g=a.id)}return g},Y:function(a,b,c){ra[b>>3]=vb;ra[c>>3]=wb},X:function(a,b){return(a=0>=a||!Y?null:Y[a-1])?0<(a.buttons&
1<<b):0},ea:function(){if(Y)return 1;Ma();R=Xc;Y=[];X=null;Wc="number"==typeof devicePixelRatio&&devicePixelRatio||1;window.addEventListener("gamepadconnected",bd,!0);window.addEventListener("gamepaddisconnected",dd,!0);window.addEventListener("keydown",ed,!0);window.addEventListener("keypress",$c,!0);window.addEventListener("keyup",fd,!0);window.addEventListener("blur",gd,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Wc=
"number"==typeof devicePixelRatio&&devicePixelRatio||1;X&&X.Ob&&N(X.Ob)(X.id,Wc,Wc)})();f.canvas.addEventListener("touchmove",hd,!0);f.canvas.addEventListener("touchstart",md,!0);f.canvas.addEventListener("touchcancel",nd,!0);f.canvas.addEventListener("touchend",nd,!0);f.canvas.addEventListener("mousemove",hd,!0);f.canvas.addEventListener("mousedown",md,!0);f.canvas.addEventListener("mouseup",nd,!0);f.canvas.addEventListener("wheel",od,!0);f.canvas.addEventListener("mousewheel",od,!0);f.canvas.addEventListener("mouseenter",
jd,!0);f.canvas.addEventListener("mouseleave",kd,!0);f.canvas.addEventListener("drop",sd,!0);f.canvas.addEventListener("dragover",td,!0);Ab.push((b,c)=>{if(X){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.Jb=X.x,X.Kb=X.y,X.Ib=X.width,X.Hb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.kb=!0):1==X.kb?(X.x=X.Jb,X.y=X.Kb,X.width=X.Ib,X.height=X.Hb,X.kb=!1):X.width!=b||X.height!=c?(X.width=b,X.height=c):d=!1;d&&(Bb(X.width,
X.height,!0),X&&X.Pb&&N(X.Pb)(X.id,X.width,X.height),X&&X.yb&&N(X.yb)(X.id,X.width,X.height))}});return 1},ba:function(){},U:function(){},_:function(a,b){if(a=0>=a||!Y?null:Y[a-1]){var c=a.ab;a.ab=b;b=c}else b=null;return b},V:function(){},ca:function(){window.removeEventListener("gamepadconnected",bd,!0);window.removeEventListener("gamepaddisconnected",dd,!0);window.removeEventListener("keydown",ed,!0);window.removeEventListener("keypress",$c,!0);window.removeEventListener("keyup",fd,!0);window.removeEventListener("blur",
gd,!0);f.canvas.removeEventListener("touchmove",hd,!0);f.canvas.removeEventListener("touchstart",md,!0);f.canvas.removeEventListener("touchcancel",nd,!0);f.canvas.removeEventListener("touchend",nd,!0);f.canvas.removeEventListener("mousemove",hd,!0);f.canvas.removeEventListener("mousedown",md,!0);f.canvas.removeEventListener("mouseup",nd,!0);f.canvas.removeEventListener("wheel",od,!0);f.canvas.removeEventListener("mousewheel",od,!0);f.canvas.removeEventListener("mouseenter",jd,!0);f.canvas.removeEventListener("mouseleave",
kd,!0);f.canvas.removeEventListener("drop",sd,!0);f.canvas.removeEventListener("dragover",td,!0);f.canvas.width=f.canvas.height=1;X=Y=null},n:function(a,b){R[a]=b},G:function(a,b,c,d){return xd(a,b,c,d)}};
(function(){function a(c){c=c.exports;f.asm=c;ma=f.asm.ha;sa();ta=f.asm.ua;va.unshift(f.asm.ia);F--;f.monitorRunDependencies&&f.monitorRunDependencies(F);if(0==F&&(null!==za&&(clearInterval(za),za=null),Aa)){var d=Aa;Aa=null;d()}return c}var b={a:yd};F++;f.monitorRunDependencies&&f.monitorRunDependencies(F);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return u("Module.instantiateWasm callback failed with error: "+c),!1}Ga(b,function(c){a(c.instance)});return{}})();
var ac=f._malloc=function(){return(ac=f._malloc=f.asm.ja).apply(null,arguments)},rd=f._free=function(){return(rd=f._free=f.asm.ka).apply(null,arguments)};f._resizeWindow=function(){return(f._resizeWindow=f.asm.la).apply(null,arguments)};f._updateImage=function(){return(f._updateImage=f.asm.ma).apply(null,arguments)};f._isModelEmpty=function(){return(f._isModelEmpty=f.asm.na).apply(null,arguments)};f._getFileSize=function(){return(f._getFileSize=f.asm.oa).apply(null,arguments)};
f._generateSTL=function(){return(f._generateSTL=f.asm.pa).apply(null,arguments)};f._generatePLY=function(){return(f._generatePLY=f.asm.qa).apply(null,arguments)};f._generateOBJ=function(){return(f._generateOBJ=f.asm.ra).apply(null,arguments)};f._generateGLB=function(){return(f._generateGLB=f.asm.sa).apply(null,arguments)};var zd=f._main=function(){return(zd=f._main=f.asm.ta).apply(null,arguments)};function Ad(){return(Ad=f.asm.va).apply(null,arguments)}
function Bd(){return(Bd=f.asm.wa).apply(null,arguments)}function Cd(){return(Cd=f.asm.xa).apply(null,arguments)}
f.ccall=function(a,b,c,d){var e={string:n=>{var t=0;if(null!==n&&void 0!==n&&0!==n){t=Zb(n)+1;var v=Cd(t);Vb(n,C,v,t);t=v}return t},array:n=>{var t=Cd(n.length);B.set(n,t);return t}};a=f["_"+a];var g=[],k=0;if(d)for(var p=0;p<d.length;p++){var q=e[c[p]];q?(0===k&&(k=Ad()),g[p]=q(d[p])):g[p]=d[p]}c=a.apply(null,g);return c=function(n){0!==k&&Bd(k);return"string"===b?I(n):"boolean"===b?!!n:n}(c)};var Dd;Aa=function Ed(){Dd||Fd();Dd||(Aa=Ed)};
function Fd(){function a(){if(!Dd&&(Dd=!0,f.calledRun=!0,!y)){f.noFSInit||Rc||(Rc=!0,Qc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Vc("stdin",f.stdin):Mc("/dev/tty","/dev/stdin"),f.stdout?Vc("stdout",null,f.stdout):Mc("/dev/tty","/dev/stdout"),f.stderr?Vc("stderr",null,f.stderr):Mc("/dev/tty1","/dev/stderr"),Oc("/dev/stdin",0),Oc("/dev/stdout",1),Oc("/dev/stderr",1));zc=!1;Ha(va);Ha(wa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Gd){var b=zd;try{var c=b(0,0);na=c;Oa(c)}catch(d){Na(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),xa.unshift(b);Ha(xa)}}if(!(0<F)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ha(ua);0<F||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Gd=!0;f.noInitialRun&&(Gd=!1);Fd();
