var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=(a,b)=>{throw b;},ca="object"==typeof window,k="function"==typeof importScripts,l="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n="",da,ea,fa;
if(l){var fs=require("fs"),ha=require("path");n=k?ha.dirname(n)+"/":__dirname+"/";da=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};fa=a=>{a=da(a,!0);a.buffer||(a=new Uint8Array(a));return a};ea=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof ia||a.context instanceof ia))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ba=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(ca||k)k?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
k&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var r=f.print||console.log.bind(console),v=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.quit&&(ba=f.quit);var ja;f.wasmBinary&&(ja=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");var ka,z=!1,la,A,B,ma,C,D,na,oa;function pa(){var a=ka.buffer;f.HEAP8=A=new Int8Array(a);f.HEAP16=ma=new Int16Array(a);f.HEAP32=C=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=na=new Float32Array(a);f.HEAPF64=oa=new Float64Array(a)}var qa,ra=[],sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();ra.unshift(a)}
var E=0,wa=null,xa=null;function w(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";v(a);z=!0;la=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="index.wasm";if(!ya(F)){var za=F;F=f.locateFile?f.locateFile(za,n):n+za}function Aa(a){try{if(a==F&&ja)return new Uint8Array(ja);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function Ba(a){if(!ja&&(ca||k)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(ea)return new Promise((b,c)=>{ea(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v("failed to asynchronously prepare wasm: "+d);w(d)})}
function Da(a,b){var c=F;ja||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||c.startsWith("file://")||l||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v("wasm streaming compile failed: "+e);v("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ea(a){for(;0<a.length;)a.shift()(f)}f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return A[a>>0];case "i8":return A[a>>0];case "i16":return ma[a>>1];case "i32":return C[a>>2];case "i64":return C[a>>2];case "float":return na[a>>2];case "double":return oa[a>>3];case "*":return D[a>>2];default:w("invalid type for getValue: "+b)}};var Fa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function H(a,b){return a?G(B,a,b):""}
function Ga(a){this.wa=a-24;this.Mb=function(b){D[this.wa+4>>2]=b};this.Lb=function(b){D[this.wa+8>>2]=b};this.ua=function(b,c){this.Kb();this.Mb(b);this.Lb(c)};this.Kb=function(){D[this.wa+16>>2]=0}}var Ha=0,Ia=0,Ja;Ja=l?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function Ka(a){a instanceof ia||"unwind"==a||ba(1,a)}function La(a){la=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);z=!0}ba(a,new ia(a))}
function Ma(a){if(!z)try{if(a(),!noExitRuntime)try{la=a=la,La(a)}catch(b){Ka(b)}}catch(b){Ka(b)}}function Na(a){setTimeout(()=>{Ma(a)},1E4)}function Oa(a){Pa||(Pa={});Pa[a]||(Pa[a]=1,l&&(a="warning: "+a),v(a))}var Pa,Qa=!1,I=null,J=0,Ra=null,Sa=0,Ta=0,Ua=0,K=0,Va=[],Wa={},Xa,Ya,Za,$a=!1,ab=!1,bb=[];
function cb(){function a(){ab=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!db){db=!0;try{eb=!0}catch(c){eb=!1,v("warning: no blob constructor, cannot create blobs with mimetypes")}fb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:eb?null:v("warning: no BlobBuilder");gb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.pb||"undefined"!=typeof gb||(v("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.pb=!0);f.preloadPlugins.push({canHandle:function(c){return!f.pb&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(eb)try{h=new Blob([c],{type:hb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:hb(d)}))}catch(p){Oa("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new fb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=gb.createObjectURL(h),q=new Image;q.onload=()=>{q.complete||w("Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=q.width;p.height=q.height;p.getContext("2d").drawImage(q,0,0);gb.revokeObjectURL(m);e&&e(c)};q.onerror=()=>{r("Image "+m+" could not be decoded");g&&g()};q.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.ic&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,g){function h(){q||(q=!0,e&&e(c))}function m(){q||(q=!0,new Audio,g&&g())}var q=!1;if(eb){try{var p=new Blob([c],{type:hb(d)})}catch(u){return m()}p=gb.createObjectURL(p);var t=new Audio;t.addEventListener("canplaythrough",()=>h(t),!1);t.onerror=function(){if(!q){v("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",x=0,y=0,Q=0;Q<c.length;Q++)for(x=x<<8|c[Q],y+=8;6<=y;){var jb=x>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[jb]}2==
y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(x&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(x&15)<<2],u+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+u;h(t)}};t.src=p;Na(()=>{h(t)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!ab&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ib(a,b,c,d){if(b&&f.Da&&a==f.canvas)return f.Da;var e;if(b){var g={antialias:!1,alpha:!1,Hb:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof kb&&(e=lb(a,g)))var m=mb[e].Ga}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof L||w("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Da=m,b&&(M=mb[e],f.Da=L=M&&M.Ga),f.kc=b,bb.forEach(q=>q()),cb());return m}var nb=!1,ob=void 0,pb=void 0;
function qb(a,b){function c(){$a=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=rb,ob&&d.requestPointerLock(),$a=!0,pb?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=D[SDL.screen>>2]|8388608),sb(f.canvas),tb()):sb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),pb?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=D[SDL.screen>>2]&
-8388609),sb(f.canvas),tb()):sb(d));if(f.onFullScreen)f.onFullScreen($a);if(f.onFullscreen)f.onFullscreen($a)}ob=a;pb=b;"undefined"==typeof ob&&(ob=!0);"undefined"==typeof pb&&(pb=!1);var d=f.canvas;nb||(nb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function rb(){if(!$a)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ub=0;function vb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ub)ub=b+1E3/60;else for(;b+2>=ub;)ub+=1E3/60;setTimeout(a,Math.max(ub-b,0))}}
function hb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var wb=0,xb=0,yb=0,zb=0;
function Ab(a){if(ab)"mousemove"!=a.type&&"mozMovementX"in a?yb=zb=0:(yb=a.movementX||a.mozMovementX||a.webkitMovementX||0,zb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(wb=SDL.ec+yb,xb=SDL.fc+zb):(wb+=yb,xb+=zb);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,yb=e-wb,zb=a-xb,wb=e,xb=a)}}var Bb=[];function tb(){var a=f.canvas;Bb.forEach(b=>b(a.width,a.height))}function Cb(a,b,c){sb(f.canvas,a,b);c||tb()}
function sb(a,b,c){b&&c?(a.Qb=b,a.Fb=c):(b=a.Qb,c=a.Fb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}pb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var db,eb,fb,gb;
function Db(a,b){Ta=a;Ua=b;if(Ra)if(Qa||(Qa=!0),0==a)I=function(){var d=Math.max(0,Ya+b-Ja())|0;setTimeout(Za,d)};else if(1==a)I=function(){vb(Za)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);k?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}I=function(){setImmediate(Za)}}}
function Eb(a,b,c,d,e){!Ra||w("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ra=a;Sa=d;var g=J;Qa=!1;Za=function(){if(!z)if(0<Va.length){var h=Date.now(),m=Va.shift();m.ac(m.Tb);if(Xa){var q=Xa,p=0==q%1?q-1:Math.floor(q);Xa=m.Wb?p:(8*q+(p+.5))/9}r('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||"Please wait...",
m=Xa,q=Wa.$b,m?m<q?f.setStatus(h+" ("+(q-m)+"/"+q+")"):f.setStatus(h):f.setStatus(""));g<J||setTimeout(Za,0)}else if(!(g<J))if(K=K+1|0,1==Ta&&1<Ua&&0!=K%Ua)I();else{0==Ta&&(Ya=Ja());if(M)for(h=M.Ba,M.Ba=M.Ea,M.Ea=h,h=M.xa,M.xa=M.Oa,M.Oa=h,h=Fb(2097152),m=0;m<=h;++m)M.xa[m]=0;z||f.preMainLoop&&!1===f.preMainLoop()||(Ma(a),f.postMainLoop&&f.postMainLoop());g<J||("object"==typeof SDL&&SDL.audio&&SDL.audio.Nb&&SDL.audio.Nb(),I())}};e||(b&&0<b?Db(0,1E3/b):Db(1,1),I());if(c)throw"unwind";}
function N(a){return qa.get(a)}var Gb=[null,[],[]],Hb=1,Ib=[],O=[],P=[],Jb=[],mb=[],Kb=[1,1,2,2,4,4,4,2,3,4,8];function R(a){Lb||(Lb=a)}function Mb(a){for(var b=Hb++,c=a.length;c<b;c++)a[c]=null;return b}function Fb(a){return 32-Math.clz32(0===a?0:a-1)}function lb(a,b){a.ua||(a.ua=a.getContext,a.getContext=function(d,e){e=a.ua(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Nb(c,b):0}
function Nb(a,b){var c=Mb(mb),d={cc:c,attributes:b,version:b.Hb,Ga:a};a.canvas&&(a.canvas.Rb=d);mb[c]=d;("undefined"==typeof b.Db||b.Db)&&Ob(d);d.kb=d.Ga.getParameter(34921);d.Ca=[];for(a=0;a<d.kb;a++)d.Ca[a]={enabled:!1,Pa:!1,size:0,type:0,qb:0,Xa:0,wa:0,xb:null};a=Fb(2097152);d.xa=[];d.Oa=[];d.xa.length=d.Oa.length=a+1;d.Ba=[];d.Ea=[];d.Ba.length=d.Ea.length=a+1;d.Aa=[];d.Aa.length=a+1;for(b=0;b<=a;++b){d.Aa[b]=null;d.xa[b]=d.Oa[b]=0;d.Ba[b]=[];d.Ea[b]=[];var e=d.Ba[b],g=d.Ea[b];e.length=g.length=
64;for(var h=0;64>h;++h)e[h]=g[h]=null}return c}
function Ob(a){a||(a=M);if(!a.Gb){a.Gb=!0;var b=a.Ga;b.Zb=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.dc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.cb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.cb)b.cb=b.getExtension("EXT_disjoint_timer_query");b.hc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var kb={},Lb,M,Pb;function Qb(a,b,c,d){for(var e=0;e<a;e++){var g=L[c](),h=g&&Mb(d);g?(g.name=h,d[h]=g):R(1282);C[b+4*e>>2]=h}}
function Rb(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Sb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Tb(a){var b=L.Cb;if(b){var c=b.Fa[a];"number"==typeof c&&(b.Fa[a]=c=L.getUniformLocation(b,b.vb[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function Ub(a,b,c,d){this.id=a;this.y=this.x=0;this.Ua=!1;this.ub=this.tb=0;this.width=b;this.height=c;this.sb=b;this.rb=c;this.title=d;this.attributes=S;this.buttons=0;this.keys=[];this.Sa=[];this.$a=this.jb=this.Ta=this.Na=this.Ha=this.Ra=this.nb=this.yb=this.hb=this.zb=this.title=null}
function Vb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Wb(a){var b=Vb(a)+1,c=Xb(b);c&&Rb(a,B,c,b);return c}function Yb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(l)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}w("initRandomDevice")}
function Zb(a){return(Zb=Yb())(a)}
var $b=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ac=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$b(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},bc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},cc=a=>
{if("/"===a)return"/";a=ac(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function dc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$b(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var ec=[];function fc(a,b){ec[a]={input:[],output:[],za:b};gc(a,hc)}
var hc={open:function(a){var b=ec[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.za.fsync(a.tty)},fsync:function(a){a.tty.za.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.za.ib)throw new T(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.za.ib(a.tty)}catch(m){throw new T(29);}if(void 0===h&&0===e)throw new T(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.za.Va)throw new T(60);
try{for(var e=0;e<d;e++)a.tty.za.Va(a.tty,b[c+e])}catch(g){throw new T(29);}d&&(a.node.timestamp=Date.now());return e}},ic={ib:function(a){if(!a.input.length){var b=null;if(l){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),
null!==b&&(b+="\n"));if(!b)return null;c=Array(Vb(b)+1);b=Rb(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Va:function(a,b){null===b||10===b?(r(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(r(G(a.output,0)),a.output=[])}},jc={Va:function(a,b){null===b||10===b?(v(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(v(G(a.output,0)),a.output=[])}},U={ra:null,ta:function(){return U.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.ra||(U.ra={dir:{node:{va:U.oa.va,sa:U.oa.sa,lookup:U.oa.lookup,La:U.oa.La,rename:U.oa.rename,unlink:U.oa.unlink,rmdir:U.oa.rmdir,readdir:U.oa.readdir,symlink:U.oa.symlink},stream:{ya:U.pa.ya}},file:{node:{va:U.oa.va,sa:U.oa.sa},stream:{ya:U.pa.ya,read:U.pa.read,write:U.pa.write,Za:U.pa.Za,lb:U.pa.lb,ob:U.pa.ob}},link:{node:{va:U.oa.va,sa:U.oa.sa,readlink:U.oa.readlink},stream:{}},ab:{node:{va:U.oa.va,
sa:U.oa.sa},stream:kc}});c=lc(a,b,c,d);16384===(c.mode&61440)?(c.oa=U.ra.dir.node,c.pa=U.ra.dir.stream,c.na={}):32768===(c.mode&61440)?(c.oa=U.ra.file.node,c.pa=U.ra.file.stream,c.qa=0,c.na=null):40960===(c.mode&61440)?(c.oa=U.ra.link.node,c.pa=U.ra.link.stream):8192===(c.mode&61440)&&(c.oa=U.ra.ab.node,c.pa=U.ra.ab.stream);c.timestamp=Date.now();a&&(a.na[b]=c,a.timestamp=c.timestamp);return c},bc:function(a){return a.na?a.na.subarray?a.na.subarray(0,a.qa):new Uint8Array(a.na):new Uint8Array(0)},
eb:function(a,b){var c=a.na?a.na.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.na,a.na=new Uint8Array(b),0<a.qa&&a.na.set(c.subarray(0,a.qa),0))},Ob:function(a,b){if(a.qa!=b)if(0==b)a.na=null,a.qa=0;else{var c=a.na;a.na=new Uint8Array(b);c&&a.na.set(c.subarray(0,Math.min(b,a.qa)));a.qa=b}},oa:{va:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.qa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ab=4096;b.blocks=Math.ceil(b.size/b.Ab);return b},sa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.Ob(a,b.size)},lookup:function(){throw mc[44];},La:function(a,b,c,d){return U.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=nc(b,
c)}catch(g){}if(d)for(var e in d.na)throw new T(55);}delete a.parent.na[a.name];a.parent.timestamp=Date.now();a.name=c;b.na[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.na[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=nc(a,b),d;for(d in c.na)throw new T(55);delete a.na[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.na)a.na.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},pa:{read:function(a,b,c,d,e){var g=a.node.na;if(e>=a.node.qa)return 0;a=Math.min(a.node.qa-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===A.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.na||a.na.subarray)){if(g)return a.na=b.subarray(c,c+d),a.qa=d;if(0===a.qa&&0===e)return a.na=b.slice(c,c+d),a.qa=
d;if(e+d<=a.qa)return a.na.set(b.subarray(c,c+d),e),d}U.eb(a,e+d);if(a.na.subarray&&b.subarray)a.na.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.na[e+g]=b[c+g];a.qa=Math.max(a.qa,e+d);return d},ya:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.qa);if(0>b)throw new T(28);return b},Za:function(a,b,c){U.eb(a.node,b+c);a.node.qa=Math.max(a.node.qa,b+c)},lb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.na;if(e&2||a.buffer!==A.buffer){if(0<
c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;w();b=void 0;if(!b)throw new T(48);A.set(a,b)}else c=!1,b=a.byteOffset;return{wa:b,Sb:c}},ob:function(a,b,c,d){U.pa.write(a,b,0,d,c,!1);return 0}}},oc=null,pc={},qc=[],rc=1,sc=null,tc=!0,T=null,mc={},V=(a,b={})=>{a=dc(a);if(!a)return{path:"",node:null};b=Object.assign({gb:!0,Wa:0},b);if(8<b.Wa)throw new T(32);a=a.split("/").filter(h=>!!h);for(var c=oc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;
c=nc(c,a[e]);d=ac(d+"/"+a[e]);c.Ma&&(!g||g&&b.gb)&&(c=c.Ma.root);if(!g||b.fb)for(g=0;40960===(c.mode&61440);)if(c=uc(d),d=dc(bc(d),c),c=V(d,{Wa:b.Wa+1}).node,40<g++)throw new T(32);}return{path:d,node:c}},vc=a=>{for(var b;;){if(a===a.parent)return a=a.ta.mb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},wc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sc.length},nc=(a,b)=>{var c;if(c=(c=xc(a,"x"))?c:a.oa.lookup?0:2)throw new T(c,a);for(c=
sc[wc(a.id,b)];c;c=c.Jb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.oa.lookup(a,b)},lc=(a,b,c,d)=>{a=new yc(a,b,c,d);b=wc(a.parent.id,a.name);a.Jb=sc[b];return sc[b]=a},zc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Ac=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},xc=(a,b)=>{if(tc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Bc=(a,b)=>{try{return nc(a,b),20}catch(c){}return xc(a,
"wx")},Cc=()=>{for(var a=0;4096>=a;a++)if(!qc[a])return a;throw new T(33);},Ec=a=>{Dc||(Dc=function(){this.ua={}},Dc.prototype={},Object.defineProperties(Dc.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.ua.flags},set:function(c){this.ua.flags=c}},position:{get:function(){return this.ua.position},set:function(c){this.ua.position=c}}}));a=Object.assign(new Dc,a);var b=Cc();a.fd=b;return qc[b]=a},kc={open:a=>{a.pa=pc[a.node.rdev].pa;
a.pa.open&&a.pa.open(a)},ya:()=>{throw new T(70);}},gc=(a,b)=>{pc[a]={pa:b}},Fc=(a,b)=>{var c="/"===b,d=!b;if(c&&oc)throw new T(10);if(!c&&!d){var e=V(b,{gb:!1});b=e.path;e=e.node;if(e.Ma)throw new T(10);if(16384!==(e.mode&61440))throw new T(54);}b={type:a,jc:{},mb:b,Ib:[]};a=a.ta(b);a.ta=b;b.root=a;c?oc=a:e&&(e.Ma=b,e.ta&&e.ta.Ib.push(b))},W=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=cc(a);if(!a||"."===a||".."===a)throw new T(28);var e=Bc(d,a);if(e)throw new T(e);if(!d.oa.La)throw new T(63);return d.oa.La(d,
a,b,c)},Gc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},Hc=(a,b)=>{if(!dc(a))throw new T(44);var c=V(b,{parent:!0}).node;if(!c)throw new T(44);b=cc(b);var d=Bc(c,b);if(d)throw new T(d);if(!c.oa.symlink)throw new T(63);c.oa.symlink(c,b,a)},uc=a=>{a=V(a).node;if(!a)throw new T(44);if(!a.oa.readlink)throw new T(28);return dc(vc(a.parent),a.oa.readlink(a))},Jc=(a,b,c)=>{if(""===a)throw new T(44);if("string"==typeof b){var d=zc[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+
b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=ac(a);try{e=V(a,{fb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new T(20);}else e=W(a,c,0),d=!0;if(!e)throw new T(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new T(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ac(b)||b&512)?31:xc(e,Ac(b)):44))throw new T(c);if(b&512&&!d){c=e;c="string"==typeof c?V(c,{fb:!0}).node:c;if(!c.oa.sa)throw new T(63);
if(16384===(c.mode&61440))throw new T(31);if(32768!==(c.mode&61440))throw new T(28);if(d=xc(c,"w"))throw new T(d);c.oa.sa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Ec({node:e,path:vc(e),flags:b,seekable:!0,position:0,pa:e.pa,Pb:[],error:!1});e.pa.open&&e.pa.open(e);!f.logReadFiles||b&1||(Ic||(Ic={}),a in Ic||(Ic[a]=1));return e},Kc=(a,b,c,d)=>{var e=void 0;if(0>c||0>e)throw new T(28);if(null===a.fd)throw new T(8);if(0===(a.flags&2097155))throw new T(8);if(16384===(a.node.mode&61440))throw new T(31);
if(!a.pa.write)throw new T(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new T(8);if(!a.seekable||!a.pa.ya)throw new T(70);a.position=a.pa.ya(a,0,2);a.Pb=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new T(70);b=a.pa.write(a,b,0,c,e,d);g||(a.position+=b)},Lc=()=>{T||(T=function(a,b){this.name="ErrnoError";this.node=b;this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(a=>{mc[a]=new T(a);mc[a].stack="<generic error, no stack>"}))},
Mc,Nc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Oc=()=>{var a="/";a="string"==typeof a?a:vc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=ac(a+"/"+c);try{W(a,16895,0)}catch(d){}}}},Qc=(a,b,c)=>{a=ac("/dev/"+a);var d=Nc(!!b,!!c);Pc||(Pc=64);var e=Pc++<<8|0;gc(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,m,q)=>{for(var p=0,t=0;t<q;t++){try{var u=b()}catch(x){throw new T(29);}if(void 0===u&&0===p)throw new T(6);if(null===
u||void 0===u)break;p++;h[m+t]=u}p&&(g.node.timestamp=Date.now());return p},write:(g,h,m,q)=>{for(var p=0;p<q;p++)try{c(h[m+p])}catch(t){throw new T(29);}q&&(g.node.timestamp=Date.now());return p}});Gc(a,d,e)},Pc,Dc,Ic,X=null,Rc=null,Y=null,S=null,Sc={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,
139271:0,139272:0,139276:0};
function Tc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Uc(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Vc(a){X&&X.$a&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||N(X.$a)(X.id,a))}function Wc(a,b){if(X){var c=Tc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.Sa[a]=b;X.jb&&(d&&(b=2),N(X.jb)(X.id,c,a,b,Uc()))}}}
function Xc(){Yc()}function Zc(){Yc()}function $c(a){Wc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ad(a){Wc(a.keyCode,0)}function bd(){if(X)for(var a=0;a<X.Sa.length;++a)X.Sa[a]&&Wc(a,0)}function cd(a){X&&(Ab(a),a.target==f.canvas&&X.Ra&&X.Ra&&N(X.Ra)(X.id,wb,xb))}function dd(a){X&&a.target==f.canvas&&X.Ha&&N(X.Ha)(X.id,1)}function ed(a){X&&a.target==f.canvas&&X.Ha&&N(X.Ha)(X.id,0)}
function fd(a,b){if(X&&(Ab(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.nb&&N(X.nb)(X.id,c,b,Uc())}}function gd(a){X&&fd(a,1)}function hd(a){X&&fd(a,0)}
function jd(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.Na&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;N(X.Na)(X.id,b,c);a.preventDefault()}}
var Z={},kd=[],ld=null;
function Yc(){if(K!==ld||!K){kd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];ld=K;for(var a=0;a<kd.length;++a){var b=kd[a];if(b){Z[a]||(r("glfw joystick connected:",a),Z[a]={id:Wb(b.id),Vb:b.buttons.length,Ub:b.axes.length,buttons:Xb(b.buttons.length),axes:Xb(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)A[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)na[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(r("glfw joystick disconnected",
a),md(Z[a].id),md(Z[a].buttons),md(Z[a].axes),delete Z[a])}}}
function nd(a){function b(m){var q="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),p=new FileReader;p.onloadend=u=>{if(2!=p.readyState)++g,r("failed to read dropped file: "+m.name+": "+p.error);else{var x=new Uint8Array(u.target.result);u={};u.flags=u.flags||577;var y=Jc(q,u.flags,u.mode);if("string"==typeof x){var Q=new Uint8Array(Vb(x)+1);x=Rb(x,Q,0,Q.length);Kc(y,Q,x,u.Bb)}else if(ArrayBuffer.isView(x))Kc(y,x,x.byteLength,u.Bb);else throw Error("Unsupported data type");if(null===y.fd)throw new T(8);
y.Eb&&(y.Eb=null);try{y.pa.close&&y.pa.close(y)}catch(jb){throw jb;}finally{qc[y.fd]=null}y.fd=null;if(++g===e){N(X.Ta)(X.id,e,c);for(u=0;u<d.length;++u)md(d[u]);md(c)}}};p.readAsArrayBuffer(m);var t=Wb(q);d.push(t);D[c+4*h>>2]=t}if(X&&X.Ta&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Xb(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Oc();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}
function od(a){if(X&&X.Ta)return a.preventDefault(),!1}f.requestFullscreen=function(a,b){qb(a,b)};f.requestAnimationFrame=function(a){vb(a)};f.setCanvasSize=function(a,b,c){Cb(a,b,c)};f.pauseMainLoop=function(){I=null;J++};f.resumeMainLoop=function(){J++;var a=Ta,b=Ua,c=Ra;Ra=null;Eb(c,0,!1,Sa,!0);Db(a,b);I()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return ib(a,b,c,d)};var L;function yc(a,b,c,d){a||(a=this);this.parent=a;this.ta=a.ta;this.Ma=null;this.id=rc++;this.name=b;this.mode=c;this.oa={};this.pa={};this.rdev=d}Object.defineProperties(yc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Lc();sc=Array(4096);Fc(U,"/");W("/tmp",16895,0);
W("/home",16895,0);W("/home/web_user",16895,0);(()=>{W("/dev",16895,0);gc(259,{read:()=>0,write:(d,e,g,h)=>h});Gc("/dev/null",259);fc(1280,ic);fc(1536,jc);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Zb(a).byteLength);return a[--b]};Qc("random",c);Qc("urandom",c);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();
(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);Fc({ta:()=>{var b=lc(a,"fd",16895,73);b.oa={lookup:(c,d)=>{var e=qc[+d];if(!e)throw new T(8);c={parent:null,ta:{mb:"fake"},oa:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var pd={a:function(a,b,c,d){w("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},k:function(a,b,c){(new Ga(a)).ua(b,c);Ha=a;Ia++;throw Ha;},E:function(){return!0},p:function(){w("")},G:Ja,H:function(a,b,c){B.copyWithin(a,b,b+c)},D:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=ka.buffer;try{ka.grow(g.call(e,2147483648,
d)-h.byteLength+65535>>>16);pa();var m=1;break a}catch(q){}m=void 0}if(m)return!0}return!1},T:function(a,b,c){a=N(a);Eb(a,b,c)},F:function(){return 52},C:function(){return 70},r:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=D[b>>2],m=D[b+4>>2];b+=8;for(var q=0;q<m;q++){var p=B[h+q],t=Gb[a];0===p||10===p?((1===a?r:v)(G(t,0)),t.length=0):t.push(p)}e+=m}D[d>>2]=e;return 0},o:function(a,b){L.attachShader(O[a],P[b])},d:function(a,b){34962==a?L.bb=b:34963==a&&(L.Qa=b);35051==a?L.Xb=b:35052==a&&(L.Yb=
b);L.bindBuffer(a,Ib[b])},V:function(a){L.bindVertexArray(Jb[a]);a=L.getParameter(34965);L.Qa=a?a.name|0:0},c:function(a,b,c,d){c&&b?L.bufferData(a,B,d,c,b):L.bufferData(a,b,d)},J:function(a){L.clear(a)},I:function(a,b,c,d){L.clearColor(a,b,c,d)},t:function(a){L.compileShader(P[a])},B:function(){var a=Mb(O),b=L.createProgram();b.name=a;b.Ka=b.Ia=b.Ja=0;b.Ya=1;O[a]=b;return a},y:function(a){var b=Mb(P);P[b]=L.createShader(a);return b},w:function(a){if(a){var b=P[a];b?(L.deleteShader(b),P[a]=null):
R(1281)}},K:function(a){L.depthFunc(a)},x:function(a,b){L.detachShader(O[a],P[b])},e:function(a){M.Ca[a].enabled=!1;L.disableVertexAttribArray(a)},m:function(a,b,c,d){if(!L.Qa){var e=1*Kb[c-5120]*b;var g=Fb(e);var h=M.Aa[g];h?g=h:(h=L.getParameter(34965),M.Aa[g]=L.createBuffer(),L.bindBuffer(34963,M.Aa[g]),L.bufferData(34963,1<<g,35048),L.bindBuffer(34963,h),g=M.Aa[g]);L.bindBuffer(34963,g);L.bufferSubData(34963,0,B.subarray(d,d+e));d=0}Pb=!1;for(e=0;e<M.kb;++e)if(g=M.Ca[e],g.Pa&&g.enabled){Pb=!0;
h=g.Xa;h=0<h?b*h:g.size*Kb[g.type-5120]*b;var m=Fb(h);var q=M.Ba[m],p=M.xa[m];M.xa[m]=M.xa[m]+1&63;var t=q[p];t?m=t:(t=L.getParameter(34964),q[p]=L.createBuffer(),L.bindBuffer(34962,q[p]),L.bufferData(34962,1<<m,35048),L.bindBuffer(34962,t),m=q[p]);L.bindBuffer(34962,m);L.bufferSubData(34962,0,B.subarray(g.wa,g.wa+h));g.xb.call(L,e,g.size,g.type,g.qb,g.Xa,0)}L.drawElements(a,b,c,d);Pb&&L.bindBuffer(34962,Ib[L.bb]);L.Qa||L.bindBuffer(34963,null)},L:function(a){L.enable(a)},g:function(a){M.Ca[a].enabled=
!0;L.enableVertexAttribArray(a)},l:function(a,b){Qb(a,b,"createBuffer",Ib)},W:function(a,b){Qb(a,b,"createVertexArray",Jb)},h:function(a,b){return L.getAttribLocation(O[a],H(b))},$:function(a,b,c,d){a=L.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?Rb(a,B,d,b):0;c&&(C[c>>2]=b)},z:function(a,b,c){if(c)if(a>=Hb)R(1281);else if(a=O[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1;else if(35719==b){if(!a.Ka)for(b=0;b<L.getProgramParameter(a,35718);++b)a.Ka=
Math.max(a.Ka,L.getActiveUniform(a,b).name.length+1);C[c>>2]=a.Ka}else if(35722==b){if(!a.Ia)for(b=0;b<L.getProgramParameter(a,35721);++b)a.Ia=Math.max(a.Ia,L.getActiveAttrib(a,b).name.length+1);C[c>>2]=a.Ia}else if(35381==b){if(!a.Ja)for(b=0;b<L.getProgramParameter(a,35382);++b)a.Ja=Math.max(a.Ja,L.getActiveUniformBlockName(a,b).length+1);C[c>>2]=a.Ja}else C[c>>2]=L.getProgramParameter(a,b);else R(1281)},q:function(a,b,c,d){a=L.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Rb(a,
B,d,b):0;c&&(C[c>>2]=b)},s:function(a,b,c){c?35716==b?(a=L.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),C[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(P[a]),C[c>>2]=a?a.length+1:0):C[c>>2]=L.getShaderParameter(P[a],b):R(1281)},b:function(a,b){b=H(b);if(a=O[a]){var c=a,d=c.Fa,e=c.wb,g;if(!d)for(c.Fa=d={},c.vb={},g=0;g<L.getProgramParameter(c,35718);++g){var h=L.getActiveUniform(c,g);var m=h.name;h=h.size;var q=Sb(m);q=0<q?m.slice(0,q):m;var p=c.Ya;c.Ya+=h;e[q]=[h,p];for(m=0;m<h;++m)d[p]=
m,c.vb[p++]=q}c=a.Fa;d=0;e=b;g=Sb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.wb[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else R(1281);return-1},A:function(a){a=O[a];L.linkProgram(a);a.Fa=0;a.wb={}},u:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?C[d+4*g>>2]:-1;e+=H(C[c+4*g>>2],0>h?void 0:h)}L.shaderSource(P[a],e)},i:function(a,b){L.uniform1f(Tb(a),b)},S:function(a,b){L.uniform1i(Tb(a),b)},R:function(a,b,c,d){L.uniform3f(Tb(a),b,c,d)},n:function(a,
b,c,d){b&&L.uniformMatrix4fv(Tb(a),!!c,na,d>>2,16*b)},j:function(a){a=O[a];L.useProgram(a);L.Cb=a},f:function(a,b,c,d,e,g){var h=M.Ca[a];L.bb?(h.Pa=!1,L.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.qb=d,h.Xa=e,h.wa=g,h.Pa=!0,h.xb=function(m,q,p,t,u,x){this.vertexAttribPointer(m,q,p,t,u,x)})},O:function(a,b,c,d){L.viewport(a,b,c,d)},Z:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||
0>=b)g=0;else{d?qb():Cb(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<S[139265];e==Y.length&&(d?f.Da=ib(f.canvas,!0,!0,{antialias:1<S[135181],depth:0<S[135173],stencil:0<S[135174],alpha:0<S[135172]}):cb());!f.Da&&d?g=0:(a=new Ub(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,X=a,g=a.id)}return g},Q:function(a,b,c){oa[b>>3]=wb;oa[c>>3]=xb},P:function(a,b){return(a=0>=a||!Y?null:Y[a-1])?0<(a.buttons&1<<b):0},_:function(){if(Y)return 1;Ja();S=Sc;Y=[];X=null;Rc="number"==typeof devicePixelRatio&&devicePixelRatio||
1;window.addEventListener("gamepadconnected",Xc,!0);window.addEventListener("gamepaddisconnected",Zc,!0);window.addEventListener("keydown",$c,!0);window.addEventListener("keypress",Vc,!0);window.addEventListener("keyup",ad,!0);window.addEventListener("blur",bd,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Rc="number"==typeof devicePixelRatio&&devicePixelRatio||1;X&&X.yb&&N(X.yb)(X.id,Rc,Rc)})();f.canvas.addEventListener("touchmove",
cd,!0);f.canvas.addEventListener("touchstart",gd,!0);f.canvas.addEventListener("touchcancel",hd,!0);f.canvas.addEventListener("touchend",hd,!0);f.canvas.addEventListener("mousemove",cd,!0);f.canvas.addEventListener("mousedown",gd,!0);f.canvas.addEventListener("mouseup",hd,!0);f.canvas.addEventListener("wheel",jd,!0);f.canvas.addEventListener("mousewheel",jd,!0);f.canvas.addEventListener("mouseenter",dd,!0);f.canvas.addEventListener("mouseleave",ed,!0);f.canvas.addEventListener("drop",nd,!0);f.canvas.addEventListener("dragover",
od,!0);Bb.push((b,c)=>{if(X){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.tb=X.x,X.ub=X.y,X.sb=X.width,X.rb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.Ua=!0):1==X.Ua?(X.x=X.tb,X.y=X.ub,X.width=X.sb,X.height=X.rb,X.Ua=!1):X.width!=b||X.height!=c?(X.width=b,X.height=c):d=!1;d&&(Cb(X.width,X.height,!0),X&&X.zb&&N(X.zb)(X.id,X.width,X.height),X&&X.hb&&N(X.hb)(X.id,X.width,X.height))}});return 1},X:function(){},M:function(){},
U:function(a,b){if(a=0>=a||!Y?null:Y[a-1]){var c=a.Na;a.Na=b;b=c}else b=null;return b},N:function(){},Y:function(){window.removeEventListener("gamepadconnected",Xc,!0);window.removeEventListener("gamepaddisconnected",Zc,!0);window.removeEventListener("keydown",$c,!0);window.removeEventListener("keypress",Vc,!0);window.removeEventListener("keyup",ad,!0);window.removeEventListener("blur",bd,!0);f.canvas.removeEventListener("touchmove",cd,!0);f.canvas.removeEventListener("touchstart",gd,!0);f.canvas.removeEventListener("touchcancel",
hd,!0);f.canvas.removeEventListener("touchend",hd,!0);f.canvas.removeEventListener("mousemove",cd,!0);f.canvas.removeEventListener("mousedown",gd,!0);f.canvas.removeEventListener("mouseup",hd,!0);f.canvas.removeEventListener("wheel",jd,!0);f.canvas.removeEventListener("mousewheel",jd,!0);f.canvas.removeEventListener("mouseenter",dd,!0);f.canvas.removeEventListener("mouseleave",ed,!0);f.canvas.removeEventListener("drop",nd,!0);f.canvas.removeEventListener("dragover",od,!0);f.canvas.width=f.canvas.height=
1;X=Y=null},v:function(a,b){S[a]=b}};
(function(){function a(c){c=c.exports;f.asm=c;ka=f.asm.aa;pa();qa=f.asm.ha;sa.unshift(f.asm.ba);E--;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(0==E&&(null!==wa&&(clearInterval(wa),wa=null),xa)){var d=xa;xa=null;d()}return c}var b={a:pd};E++;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return v("Module.instantiateWasm callback failed with error: "+c),!1}Da(b,function(c){a(c.instance)});return{}})();
f._gl_test=function(){return(f._gl_test=f.asm.ca).apply(null,arguments)};f._add=function(){return(f._add=f.asm.da).apply(null,arguments)};f._list=function(){return(f._list=f.asm.ea).apply(null,arguments)};f._liststr=function(){return(f._liststr=f.asm.fa).apply(null,arguments)};var qd=f._main=function(){return(qd=f._main=f.asm.ga).apply(null,arguments)},Xb=f._malloc=function(){return(Xb=f._malloc=f.asm.ia).apply(null,arguments)},md=f._free=function(){return(md=f._free=f.asm.ja).apply(null,arguments)};
function rd(){return(rd=f.asm.ka).apply(null,arguments)}function sd(){return(sd=f.asm.la).apply(null,arguments)}function td(){return(td=f.asm.ma).apply(null,arguments)}
f.ccall=function(a,b,c,d){var e={string:p=>{var t=0;if(null!==p&&void 0!==p&&0!==p){t=Vb(p)+1;var u=td(t);Rb(p,B,u,t);t=u}return t},array:p=>{var t=td(p.length);A.set(p,t);return t}};a=f["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var q=e[c[m]];q?(0===h&&(h=rd()),g[m]=q(d[m])):g[m]=d[m]}c=a.apply(null,g);return c=function(p){0!==h&&sd(h);return"string"===b?H(p):"boolean"===b?!!p:p}(c)};var ud;xa=function vd(){ud||wd();ud||(xa=vd)};
function wd(){function a(){if(!ud&&(ud=!0,f.calledRun=!0,!z)){f.noFSInit||Mc||(Mc=!0,Lc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Qc("stdin",f.stdin):Hc("/dev/tty","/dev/stdin"),f.stdout?Qc("stdout",null,f.stdout):Hc("/dev/tty","/dev/stdout"),f.stderr?Qc("stderr",null,f.stderr):Hc("/dev/tty1","/dev/stderr"),Jc("/dev/stdin",0),Jc("/dev/stdout",1),Jc("/dev/stderr",1));tc=!1;Ea(sa);Ea(ta);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(xd){var b=qd;try{var c=b(0,0);la=c;La(c)}catch(d){Ka(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),ua.unshift(b);Ea(ua)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Ea(ra);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var xd=!0;f.noInitialRun&&(xd=!1);wd();
