var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=(a,b)=>{throw b;},ca="object"==typeof window,k="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ea,fa,ha;
if(da){var fs=require("fs"),ia=require("path");l=k?ia.dirname(l)+"/":__dirname+"/";ea=(a,b)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ha=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};fa=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof ja||a.context instanceof ja))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ba=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(ca||k)k?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
k&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var n=f.print||console.log.bind(console),r=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.quit&&(ba=f.quit);var ka;f.wasmBinary&&(ka=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&v("no native wasm support detected");var la,w=!1,ma,y,z,na,B,C,oa,pa;function qa(){var a=la.buffer;f.HEAP8=y=new Int8Array(a);f.HEAP16=na=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=z=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=C=new Uint32Array(a);f.HEAPF32=oa=new Float32Array(a);f.HEAPF64=pa=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();sa.unshift(a)}
var D=0,xa=null,ya=null;function v(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";r(a);w=!0;ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function za(a){return a.startsWith("data:application/octet-stream;base64,")}var E;E="index.wasm";if(!za(E)){var Aa=E;E=f.locateFile?f.locateFile(Aa,l):l+Aa}function Ba(a){try{if(a==E&&ka)return new Uint8Array(ka);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){v(b)}}
function Ca(a){if(!ka&&(ca||k)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ba(a));if(fa)return new Promise((b,c)=>{fa(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ba(a))}function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r("failed to asynchronously prepare wasm: "+d);v(d)})}
function Ea(a,b){var c=E;ka||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||c.startsWith("file://")||da||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r("wasm streaming compile failed: "+e);r("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Fa(a){for(;0<a.length;)a.shift()(f)}f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a>>0];case "i8":return y[a>>0];case "i16":return na[a>>1];case "i32":return B[a>>2];case "i64":return B[a>>2];case "float":return oa[a>>2];case "double":return pa[a>>3];case "*":return C[a>>2];default:v(`invalid type for getValue: ${b}`)}};var Ga="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?F(z,a,b):""}
function Ha(a){this.wa=a-24;this.Lb=function(b){C[this.wa+4>>2]=b};this.Kb=function(b){C[this.wa+8>>2]=b};this.ua=function(b,c){this.Jb();this.Lb(b);this.Kb(c)};this.Jb=function(){C[this.wa+16>>2]=0}}var Ia=0,Ja=0,Ka;Ka=da?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function La(a){a instanceof ja||"unwind"==a||ba(1,a)}function Ma(a){ma=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);w=!0}ba(a,new ja(a))}
function Na(a){if(!w)try{if(a(),!noExitRuntime)try{ma=a=ma,Ma(a)}catch(b){La(b)}}catch(b){La(b)}}function Oa(a){setTimeout(()=>{Na(a)},1E4)}var Pa=f.preloadPlugins||[],Qa=!1,H=null,I=0,Ra=null,Sa=0,Ta=0,Ua=0,J=0,Va=[],Wa={},Xa,Ya,Za,$a=!1,ab=!1,bb=[];
function cb(){function a(){ab=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!db){db=!0;Pa.push({canHandle:function(c){return!f.ic&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=new Blob([c],{type:eb(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:eb(d)}));var m=URL.createObjectURL(h),q=new Image;q.onload=()=>{q.complete||v("Image "+
d+" could not be decoded");var p=document.createElement("canvas");p.width=q.width;p.height=q.height;p.getContext("2d").drawImage(q,0,0);URL.revokeObjectURL(m);e&&e(c)};q.onerror=()=>{n("Image "+m+" could not be decoded");g&&g()};q.src=m}});Pa.push({canHandle:function(c){return!f.hc&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){h||(h=!0,e&&e(c))}var h=!1,m=URL.createObjectURL(new Blob([c],{type:eb(d)})),q=new Audio;q.addEventListener("canplaythrough",()=>g(q),!1);
q.onerror=function(){if(!h){r("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var p="",t=0,u=0,x=0;x<c.length;x++)for(t=t<<8|c[x],u+=8;6<=u;){var A=t>>u-6&63;u-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==u?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==u&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");q.src="data:audio/x-"+d.substr(-3)+
";base64,"+p;g(q)}};q.src=m;Oa(()=>{g(q)})}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!ab&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function fb(a,b,c,d){if(b&&f.Da&&a==f.canvas)return f.Da;var e;if(b){var g={antialias:!1,alpha:!1,Gb:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof gb&&(e=hb(a,g)))var m=ib[e].Ga}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||v("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Da=m,b&&(L=ib[e],f.Da=K=L&&L.Ga),f.kc=b,bb.forEach(q=>q()),cb());return m}var jb=!1,kb=void 0,M=void 0;
function lb(a,b){function c(){$a=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=mb,kb&&d.requestPointerLock(),$a=!0,M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),nb(f.canvas),ob()):nb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]&-8388609),
nb(f.canvas),ob()):nb(d));if(f.onFullScreen)f.onFullScreen($a);if(f.onFullscreen)f.onFullscreen($a)}kb=a;M=b;"undefined"==typeof kb&&(kb=!0);"undefined"==typeof M&&(M=!1);var d=f.canvas;jb||(jb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function mb(){if(!$a)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var pb=0;
function qb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===pb)pb=b+1E3/60;else for(;b+2>=pb;)pb+=1E3/60;setTimeout(a,Math.max(pb-b,0))}}function eb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var N=0,rb=0,tb=0,ub=0;
function vb(a){if(ab)"mousemove"!=a.type&&"mozMovementX"in a?tb=ub=0:(tb=a.movementX||a.mozMovementX||a.webkitMovementX||0,ub=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(N=SDL.dc+tb,rb=SDL.ec+ub):(N+=tb,rb+=ub);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==a.type&&
"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,tb=e-N,ub=a-rb,N=e,rb=a)}}var wb=[];function ob(){var a=f.canvas;wb.forEach(b=>b(a.width,a.height))}function xb(a,b,c){nb(f.canvas,a,b);c||ob()}
function nb(a,b,c){b&&c?(a.Pb=b,a.Eb=c):(b=a.Pb,c=a.Eb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}M?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var db;
function yb(a,b){Ta=a;Ua=b;if(Ra)if(Qa||(Qa=!0),0==a)H=function(){var d=Math.max(0,Ya+b-Ka())|0;setTimeout(Za,d)};else if(1==a)H=function(){qb(Za)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);k?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}H=function(){setImmediate(Za)}}}
function zb(a,b,c,d,e){!Ra||v("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ra=a;Sa=d;var g=I;Qa=!1;Za=function(){if(!w)if(0<Va.length){var h=Date.now(),m=Va.shift();m.$b(m.Sb);if(Xa){var q=Xa,p=0==q%1?q-1:Math.floor(q);Xa=m.Vb?p:(8*q+(p+.5))/9}n('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||"Please wait...",
m=Xa,q=Wa.Zb,m?m<q?f.setStatus(h+" ("+(q-m)+"/"+q+")"):f.setStatus(h):f.setStatus(""));g<I||setTimeout(Za,0)}else if(!(g<I))if(J=J+1|0,1==Ta&&1<Ua&&0!=J%Ua)H();else{0==Ta&&(Ya=Ka());if(L)for(h=L.Ba,L.Ba=L.Ea,L.Ea=h,h=L.xa,L.xa=L.Oa,L.Oa=h,h=Ab(2097152),m=0;m<=h;++m)L.xa[m]=0;w||f.preMainLoop&&!1===f.preMainLoop()||(Na(a),f.postMainLoop&&f.postMainLoop());g<I||("object"==typeof SDL&&SDL.audio&&SDL.audio.Mb&&SDL.audio.Mb(),H())}};e||(b&&0<b?yb(0,1E3/b):yb(1,1),H());if(c)throw"unwind";}
function O(a){return ra.get(a)}var Bb=[null,[],[]],Cb=1,Db=[],P=[],Q=[],Eb=[],ib=[],Fb=[1,1,2,2,4,4,4,2,3,4,8];function R(a){Gb||(Gb=a)}function Hb(a){for(var b=Cb++,c=a.length;c<b;c++)a[c]=null;return b}function Ab(a){return 32-Math.clz32(0===a?0:a-1)}function hb(a,b){a.ua||(a.ua=a.getContext,a.getContext=function(d,e){e=a.ua(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Ib(c,b):0}
function Ib(a,b){var c=Hb(ib),d={bc:c,attributes:b,version:b.Gb,Ga:a};a.canvas&&(a.canvas.Qb=d);ib[c]=d;("undefined"==typeof b.Cb||b.Cb)&&Jb(d);d.kb=d.Ga.getParameter(34921);d.Ca=[];for(a=0;a<d.kb;a++)d.Ca[a]={enabled:!1,Pa:!1,size:0,type:0,pb:0,Xa:0,wa:0,wb:null};a=Ab(2097152);d.xa=[];d.Oa=[];d.xa.length=d.Oa.length=a+1;d.Ba=[];d.Ea=[];d.Ba.length=d.Ea.length=a+1;d.Aa=[];d.Aa.length=a+1;for(b=0;b<=a;++b){d.Aa[b]=null;d.xa[b]=d.Oa[b]=0;d.Ba[b]=[];d.Ea[b]=[];var e=d.Ba[b],g=d.Ea[b];e.length=g.length=
64;for(var h=0;64>h;++h)e[h]=g[h]=null}return c}
function Jb(a){a||(a=L);if(!a.Fb){a.Fb=!0;var b=a.Ga;b.Yb=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.cc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.cb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.cb)b.cb=b.getExtension("EXT_disjoint_timer_query");b.fc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var gb={},Gb,L,Kb;function Lb(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),h=g&&Hb(d);g?(g.name=h,d[h]=g):R(1282);B[b+4*e>>2]=h}}
function Mb(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Nb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Ob(a){var b=K.Bb;if(b){var c=b.Fa[a];"number"==typeof c&&(b.Fa[a]=c=K.getUniformLocation(b,b.ub[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function Pb(a,b,c,d){this.id=a;this.y=this.x=0;this.Ua=!1;this.tb=this.sb=0;this.width=b;this.height=c;this.rb=b;this.qb=c;this.title=d;this.attributes=S;this.buttons=0;this.keys=[];this.Sa=[];this.$a=this.jb=this.Ta=this.Na=this.Ha=this.Ra=this.nb=this.xb=this.hb=this.yb=this.title=null}
function Qb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Rb(a){var b=Qb(a)+1,c=Sb(b);c&&Mb(a,z,c,b);return c}function Tb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(da)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}v("initRandomDevice")}
function Ub(a){return(Ub=Tb())(a)}
var Vb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Wb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Vb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Xb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Yb=a=>
{if("/"===a)return"/";a=Wb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Zb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Vb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var $b=[];function ac(a,b){$b[a]={input:[],output:[],za:b};bc(a,cc)}
var cc={open:function(a){var b=$b[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.za.fsync(a.tty)},fsync:function(a){a.tty.za.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.za.ib)throw new T(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.za.ib(a.tty)}catch(m){throw new T(29);}if(void 0===h&&0===e)throw new T(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.za.Va)throw new T(60);
try{for(var e=0;e<d;e++)a.tty.za.Va(a.tty,b[c+e])}catch(g){throw new T(29);}d&&(a.node.timestamp=Date.now());return e}},dc={ib:function(a){if(!a.input.length){var b=null;if(da){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(Qb(b)+1);b=Mb(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Va:function(a,b){null===b||10===b?(n(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(n(F(a.output,0)),a.output=[])}},ec={Va:function(a,b){null===b||10===b?(r(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(r(F(a.output,0)),a.output=[])}},U={ra:null,ta:function(){return U.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.ra||(U.ra={dir:{node:{va:U.oa.va,sa:U.oa.sa,lookup:U.oa.lookup,La:U.oa.La,rename:U.oa.rename,unlink:U.oa.unlink,rmdir:U.oa.rmdir,readdir:U.oa.readdir,symlink:U.oa.symlink},stream:{ya:U.pa.ya}},file:{node:{va:U.oa.va,sa:U.oa.sa},stream:{ya:U.pa.ya,read:U.pa.read,write:U.pa.write,Za:U.pa.Za,lb:U.pa.lb,ob:U.pa.ob}},link:{node:{va:U.oa.va,sa:U.oa.sa,readlink:U.oa.readlink},stream:{}},ab:{node:{va:U.oa.va,
sa:U.oa.sa},stream:fc}});c=gc(a,b,c,d);16384===(c.mode&61440)?(c.oa=U.ra.dir.node,c.pa=U.ra.dir.stream,c.na={}):32768===(c.mode&61440)?(c.oa=U.ra.file.node,c.pa=U.ra.file.stream,c.qa=0,c.na=null):40960===(c.mode&61440)?(c.oa=U.ra.link.node,c.pa=U.ra.link.stream):8192===(c.mode&61440)&&(c.oa=U.ra.ab.node,c.pa=U.ra.ab.stream);c.timestamp=Date.now();a&&(a.na[b]=c,a.timestamp=c.timestamp);return c},ac:function(a){return a.na?a.na.subarray?a.na.subarray(0,a.qa):new Uint8Array(a.na):new Uint8Array(0)},
eb:function(a,b){var c=a.na?a.na.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.na,a.na=new Uint8Array(b),0<a.qa&&a.na.set(c.subarray(0,a.qa),0))},Nb:function(a,b){if(a.qa!=b)if(0==b)a.na=null,a.qa=0;else{var c=a.na;a.na=new Uint8Array(b);c&&a.na.set(c.subarray(0,Math.min(b,a.qa)));a.qa=b}},oa:{va:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.qa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.zb=4096;b.blocks=Math.ceil(b.size/b.zb);return b},sa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.Nb(a,b.size)},lookup:function(){throw hc[44];},La:function(a,b,c,d){return U.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ic(b,
c)}catch(g){}if(d)for(var e in d.na)throw new T(55);}delete a.parent.na[a.name];a.parent.timestamp=Date.now();a.name=c;b.na[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.na[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ic(a,b),d;for(d in c.na)throw new T(55);delete a.na[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.na)a.na.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},pa:{read:function(a,b,c,d,e){var g=a.node.na;if(e>=a.node.qa)return 0;a=Math.min(a.node.qa-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===y.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.na||a.na.subarray)){if(g)return a.na=b.subarray(c,c+d),a.qa=d;if(0===a.qa&&0===e)return a.na=b.slice(c,c+d),a.qa=
d;if(e+d<=a.qa)return a.na.set(b.subarray(c,c+d),e),d}U.eb(a,e+d);if(a.na.subarray&&b.subarray)a.na.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.na[e+g]=b[c+g];a.qa=Math.max(a.qa,e+d);return d},ya:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.qa);if(0>b)throw new T(28);return b},Za:function(a,b,c){U.eb(a.node,b+c);a.node.qa=Math.max(a.node.qa,b+c)},lb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.na;if(e&2||a.buffer!==y.buffer){if(0<
c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;v();b=void 0;if(!b)throw new T(48);y.set(a,b)}else c=!1,b=a.byteOffset;return{wa:b,Rb:c}},ob:function(a,b,c,d){U.pa.write(a,b,0,d,c,!1);return 0}}};function jc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var kc=null,lc={},mc=[],nc=1,oc=null,pc=!0,T=null,hc={},V=(a,b={})=>{a=Zb(a);if(!a)return{path:"",node:null};b=Object.assign({gb:!0,Wa:0},b);if(8<b.Wa)throw new T(32);a=a.split("/").filter(h=>!!h);for(var c=kc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=ic(c,a[e]);d=Wb(d+"/"+a[e]);c.Ma&&(!g||g&&b.gb)&&(c=c.Ma.root);if(!g||b.fb)for(g=0;40960===(c.mode&61440);)if(c=qc(d),d=Zb(Xb(d),c),c=V(d,{Wa:b.Wa+1}).node,40<g++)throw new T(32);}return{path:d,node:c}},rc=a=>{for(var b;;){if(a===
a.parent)return a=a.ta.mb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},sc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%oc.length},ic=(a,b)=>{var c;if(c=(c=tc(a,"x"))?c:a.oa.lookup?0:2)throw new T(c,a);for(c=oc[sc(a.id,b)];c;c=c.Ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.oa.lookup(a,b)},gc=(a,b,c,d)=>{a=new uc(a,b,c,d);b=sc(a.parent.id,a.name);a.Ib=oc[b];return oc[b]=a},vc=a=>{var b=["r","w","rw"][a&3];
a&512&&(b+="w");return b},tc=(a,b)=>{if(pc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},wc=(a,b)=>{try{return ic(a,b),20}catch(c){}return tc(a,"wx")},xc=()=>{for(var a=0;4096>=a;a++)if(!mc[a])return a;throw new T(33);},zc=a=>{yc||(yc=function(){this.ua={}},yc.prototype={},Object.defineProperties(yc.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.ua.flags},
set:function(c){this.ua.flags=c}},position:{get:function(){return this.ua.position},set:function(c){this.ua.position=c}}}));a=Object.assign(new yc,a);var b=xc();a.fd=b;return mc[b]=a},fc={open:a=>{a.pa=lc[a.node.rdev].pa;a.pa.open&&a.pa.open(a)},ya:()=>{throw new T(70);}},bc=(a,b)=>{lc[a]={pa:b}},Ac=(a,b)=>{var c="/"===b,d=!b;if(c&&kc)throw new T(10);if(!c&&!d){var e=V(b,{gb:!1});b=e.path;e=e.node;if(e.Ma)throw new T(10);if(16384!==(e.mode&61440))throw new T(54);}b={type:a,jc:{},mb:b,Hb:[]};a=a.ta(b);
a.ta=b;b.root=a;c?kc=a:e&&(e.Ma=b,e.ta&&e.ta.Hb.push(b))},W=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=Yb(a);if(!a||"."===a||".."===a)throw new T(28);var e=wc(d,a);if(e)throw new T(e);if(!d.oa.La)throw new T(63);return d.oa.La(d,a,b,c)},Bc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},Cc=(a,b)=>{if(!Zb(a))throw new T(44);var c=V(b,{parent:!0}).node;if(!c)throw new T(44);b=Yb(b);var d=wc(c,b);if(d)throw new T(d);if(!c.oa.symlink)throw new T(63);c.oa.symlink(c,b,a)},qc=a=>{a=V(a).node;if(!a)throw new T(44);
if(!a.oa.readlink)throw new T(28);return Zb(rc(a.parent),a.oa.readlink(a))},Ec=(a,b,c)=>{if(""===a)throw new T(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Wb(a);try{e=V(a,{fb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new T(20);}else e=W(a,c,0),d=!0;if(!e)throw new T(44);8192===(e.mode&
61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new T(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==vc(b)||b&512)?31:tc(e,vc(b)):44))throw new T(c);if(b&512&&!d){c=e;c="string"==typeof c?V(c,{fb:!0}).node:c;if(!c.oa.sa)throw new T(63);if(16384===(c.mode&61440))throw new T(31);if(32768!==(c.mode&61440))throw new T(28);if(d=tc(c,"w"))throw new T(d);c.oa.sa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=zc({node:e,path:rc(e),flags:b,seekable:!0,position:0,pa:e.pa,
Ob:[],error:!1});e.pa.open&&e.pa.open(e);!f.logReadFiles||b&1||(Dc||(Dc={}),a in Dc||(Dc[a]=1));return e},Fc=(a,b,c,d)=>{var e=void 0;if(0>c||0>e)throw new T(28);if(null===a.fd)throw new T(8);if(0===(a.flags&2097155))throw new T(8);if(16384===(a.node.mode&61440))throw new T(31);if(!a.pa.write)throw new T(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new T(8);if(!a.seekable||!a.pa.ya)throw new T(70);a.position=a.pa.ya(a,0,2);a.Ob=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new T(70);
b=a.pa.write(a,b,0,c,e,d);g||(a.position+=b)},Gc=()=>{T||(T=function(a,b){this.name="ErrnoError";this.node=b;this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(a=>{hc[a]=new T(a);hc[a].stack="<generic error, no stack>"}))},Hc,Ic=()=>{var a="/";a="string"==typeof a?a:rc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=Wb(a+"/"+c);try{W(a,16895,0)}catch(d){}}}},Kc=(a,b,c)=>{a=Wb("/dev/"+a);var d=jc(!!b,!!c);Jc||(Jc=64);var e=Jc++<<8|0;
bc(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,m,q)=>{for(var p=0,t=0;t<q;t++){try{var u=b()}catch(x){throw new T(29);}if(void 0===u&&0===p)throw new T(6);if(null===u||void 0===u)break;p++;h[m+t]=u}p&&(g.node.timestamp=Date.now());return p},write:(g,h,m,q)=>{for(var p=0;p<q;p++)try{c(h[m+p])}catch(t){throw new T(29);}q&&(g.node.timestamp=Date.now());return p}});Bc(a,d,e)},Jc,yc,Dc,X=null,Lc=null,Y=null,S=null,Mc={131073:0,131074:0,131075:1,131076:1,131077:1,
131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Nc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Oc(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Pc(a){X&&X.$a&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||O(X.$a)(X.id,a))}function Qc(a,b){if(X){var c=Nc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.Sa[a]=b;X.jb&&(d&&(b=2),O(X.jb)(X.id,c,a,b,Oc()))}}}
function Rc(){Sc()}function Tc(){Sc()}function Uc(a){Qc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Vc(a){Qc(a.keyCode,0)}function Wc(){if(X)for(var a=0;a<X.Sa.length;++a)X.Sa[a]&&Qc(a,0)}function Xc(a){X&&(vb(a),a.target==f.canvas&&X.Ra&&X.Ra&&O(X.Ra)(X.id,N,rb))}function Yc(a){X&&a.target==f.canvas&&X.Ha&&O(X.Ha)(X.id,1)}function Zc(a){X&&a.target==f.canvas&&X.Ha&&O(X.Ha)(X.id,0)}
function $c(a,b){if(X&&(vb(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.nb&&O(X.nb)(X.id,c,b,Oc())}}function ad(a){X&&$c(a,1)}function bd(a){X&&$c(a,0)}
function cd(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.Na&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;O(X.Na)(X.id,b,c);a.preventDefault()}}
var Z={},dd=[],ed=null;
function Sc(){if(J!==ed||!J){dd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];ed=J;for(var a=0;a<dd.length;++a){var b=dd[a];if(b){Z[a]||(n("glfw joystick connected:",a),Z[a]={id:Rb(b.id),Ub:b.buttons.length,Tb:b.axes.length,buttons:Sb(b.buttons.length),axes:Sb(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)y[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)oa[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(n("glfw joystick disconnected",
a),fd(Z[a].id),fd(Z[a].buttons),fd(Z[a].axes),delete Z[a])}}}
function gd(a){function b(m){var q="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),p=new FileReader;p.onloadend=u=>{if(2!=p.readyState)++g,n("failed to read dropped file: "+m.name+": "+p.error);else{var x=new Uint8Array(u.target.result);u={};u.flags=u.flags||577;var A=Ec(q,u.flags,u.mode);if("string"==typeof x){var sb=new Uint8Array(Qb(x)+1);x=Mb(x,sb,0,sb.length);Fc(A,sb,x,u.Ab)}else if(ArrayBuffer.isView(x))Fc(A,x,x.byteLength,u.Ab);else throw Error("Unsupported data type");if(null===A.fd)throw new T(8);
A.Db&&(A.Db=null);try{A.pa.close&&A.pa.close(A)}catch(qd){throw qd;}finally{mc[A.fd]=null}A.fd=null;if(++g===e){O(X.Ta)(X.id,e,c);for(u=0;u<d.length;++u)fd(d[u]);fd(c)}}};p.readAsArrayBuffer(m);var t=Rb(q);d.push(t);C[c+4*h>>2]=t}if(X&&X.Ta&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Sb(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Ic();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}
function hd(a){if(X&&X.Ta)return a.preventDefault(),!1}f.requestFullscreen=function(a,b){lb(a,b)};f.requestAnimationFrame=function(a){qb(a)};f.setCanvasSize=function(a,b,c){xb(a,b,c)};f.pauseMainLoop=function(){H=null;I++};f.resumeMainLoop=function(){I++;var a=Ta,b=Ua,c=Ra;Ra=null;zb(c,0,!1,Sa,!0);yb(a,b);H()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return fb(a,b,c,d)};var K;function uc(a,b,c,d){a||(a=this);this.parent=a;this.ta=a.ta;this.Ma=null;this.id=nc++;this.name=b;this.mode=c;this.oa={};this.pa={};this.rdev=d}Object.defineProperties(uc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Gc();oc=Array(4096);Ac(U,"/");W("/tmp",16895,0);
W("/home",16895,0);W("/home/web_user",16895,0);(()=>{W("/dev",16895,0);bc(259,{read:()=>0,write:(d,e,g,h)=>h});Bc("/dev/null",259);ac(1280,dc);ac(1536,ec);Bc("/dev/tty",1280);Bc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ub(a).byteLength);return a[--b]};Kc("random",c);Kc("urandom",c);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();
(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);Ac({ta:()=>{var b=gc(a,"fd",16895,73);b.oa={lookup:(c,d)=>{var e=mc[+d];if(!e)throw new T(8);c={parent:null,ta:{mb:"fake"},oa:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var jd={a:function(a,b,c,d){v(`Assertion failed: ${G(a)}, at: `+[b?G(b):"unknown filename",c,d?G(d):"unknown function"])},k:function(a,b,c){(new Ha(a)).ua(b,c);Ia=a;Ja++;throw Ia;},E:function(){return!0},m:function(){v("")},G:Ka,H:function(a,b,c){z.copyWithin(a,b,b+c)},D:function(a){var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=la.buffer;try{la.grow(g.call(e,2147483648,
d)-h.byteLength+65535>>>16);qa();var m=1;break a}catch(q){}m=void 0}if(m)return!0}return!1},T:function(a,b,c){a=O(a);zb(a,b,c)},F:function(){return 52},C:function(){return 70},r:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=C[b>>2],m=C[b+4>>2];b+=8;for(var q=0;q<m;q++){var p=z[h+q],t=Bb[a];0===p||10===p?((1===a?n:r)(F(t,0)),t.length=0):t.push(p)}e+=m}C[d>>2]=e;return 0},p:function(a,b){K.attachShader(P[a],Q[b])},d:function(a,b){34962==a?K.bb=b:34963==a&&(K.Qa=b);35051==a?K.Wb=b:35052==a&&(K.Xb=
b);K.bindBuffer(a,Db[b])},V:function(a){K.bindVertexArray(Eb[a]);a=K.getParameter(34965);K.Qa=a?a.name|0:0},c:function(a,b,c,d){c&&b?K.bufferData(a,z,d,c,b):K.bufferData(a,b,d)},J:function(a){K.clear(a)},I:function(a,b,c,d){K.clearColor(a,b,c,d)},t:function(a){K.compileShader(Q[a])},B:function(){var a=Hb(P),b=K.createProgram();b.name=a;b.Ka=b.Ia=b.Ja=0;b.Ya=1;P[a]=b;return a},y:function(a){var b=Hb(Q);Q[b]=K.createShader(a);return b},w:function(a){if(a){var b=Q[a];b?(K.deleteShader(b),Q[a]=null):
R(1281)}},K:function(a){K.depthFunc(a)},x:function(a,b){K.detachShader(P[a],Q[b])},e:function(a){L.Ca[a].enabled=!1;K.disableVertexAttribArray(a)},n:function(a,b,c,d){if(!K.Qa){var e=1*Fb[c-5120]*b;var g=Ab(e);var h=L.Aa[g];h?g=h:(h=K.getParameter(34965),L.Aa[g]=K.createBuffer(),K.bindBuffer(34963,L.Aa[g]),K.bufferData(34963,1<<g,35048),K.bindBuffer(34963,h),g=L.Aa[g]);K.bindBuffer(34963,g);K.bufferSubData(34963,0,z.subarray(d,d+e));d=0}Kb=!1;for(e=0;e<L.kb;++e)if(g=L.Ca[e],g.Pa&&g.enabled){Kb=!0;
h=g.Xa;h=0<h?b*h:g.size*Fb[g.type-5120]*b;var m=Ab(h);var q=L.Ba[m],p=L.xa[m];L.xa[m]=L.xa[m]+1&63;var t=q[p];t?m=t:(t=K.getParameter(34964),q[p]=K.createBuffer(),K.bindBuffer(34962,q[p]),K.bufferData(34962,1<<m,35048),K.bindBuffer(34962,t),m=q[p]);K.bindBuffer(34962,m);K.bufferSubData(34962,0,z.subarray(g.wa,g.wa+h));g.wb.call(K,e,g.size,g.type,g.pb,g.Xa,0)}K.drawElements(a,b,c,d);Kb&&K.bindBuffer(34962,Db[K.bb]);K.Qa||K.bindBuffer(34963,null)},L:function(a){K.enable(a)},g:function(a){L.Ca[a].enabled=
!0;K.enableVertexAttribArray(a)},l:function(a,b){Lb(a,b,"createBuffer",Db)},W:function(a,b){Lb(a,b,"createVertexArray",Eb)},h:function(a,b){return K.getAttribLocation(P[a],G(b))},$:function(a,b,c,d){a=K.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Mb(a,z,d,b):0;c&&(B[c>>2]=b)},z:function(a,b,c){if(c)if(a>=Cb)R(1281);else if(a=P[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.Ka)for(b=0;b<K.getProgramParameter(a,35718);++b)a.Ka=
Math.max(a.Ka,K.getActiveUniform(a,b).name.length+1);B[c>>2]=a.Ka}else if(35722==b){if(!a.Ia)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Ia=Math.max(a.Ia,K.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.Ia}else if(35381==b){if(!a.Ja)for(b=0;b<K.getProgramParameter(a,35382);++b)a.Ja=Math.max(a.Ja,K.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.Ja}else B[c>>2]=K.getProgramParameter(a,b);else R(1281)},q:function(a,b,c,d){a=K.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?Mb(a,
z,d,b):0;c&&(B[c>>2]=b)},s:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(Q[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=K.getShaderParameter(Q[a],b):R(1281)},b:function(a,b){b=G(b);if(a=P[a]){var c=a,d=c.Fa,e=c.vb,g;if(!d)for(c.Fa=d={},c.ub={},g=0;g<K.getProgramParameter(c,35718);++g){var h=K.getActiveUniform(c,g);var m=h.name;h=h.size;var q=Nb(m);q=0<q?m.slice(0,q):m;var p=c.Ya;c.Ya+=h;e[q]=[h,p];for(m=0;m<h;++m)d[p]=
m,c.ub[p++]=q}c=a.Fa;d=0;e=b;g=Nb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.vb[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},A:function(a){a=P[a];K.linkProgram(a);a.Fa=0;a.vb={}},u:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?B[d+4*g>>2]:-1;e+=G(B[c+4*g>>2],0>h?void 0:h)}K.shaderSource(Q[a],e)},i:function(a,b){K.uniform1f(Ob(a),b)},S:function(a,b){K.uniform1i(Ob(a),b)},R:function(a,b,c,d){K.uniform3f(Ob(a),b,c,d)},o:function(a,
b,c,d){b&&K.uniformMatrix4fv(Ob(a),!!c,oa,d>>2,16*b)},j:function(a){a=P[a];K.useProgram(a);K.Bb=a},f:function(a,b,c,d,e,g){var h=L.Ca[a];K.bb?(h.Pa=!1,K.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.pb=d,h.Xa=e,h.wa=g,h.Pa=!0,h.wb=function(m,q,p,t,u,x){this.vertexAttribPointer(m,q,p,t,u,x)})},O:function(a,b,c,d){K.viewport(a,b,c,d)},Z:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||
0>=b)g=0;else{d?lb():xb(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<S[139265];e==Y.length&&(d?f.Da=fb(f.canvas,!0,!0,{antialias:1<S[135181],depth:0<S[135173],stencil:0<S[135174],alpha:0<S[135172]}):cb());!f.Da&&d?g=0:(a=new Pb(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,X=a,g=a.id)}return g},Q:function(a,b,c){pa[b>>3]=N;pa[c>>3]=rb},P:function(a,b){return(a=0>=a||!Y?null:Y[a-1])?0<(a.buttons&1<<b):0},_:function(){if(Y)return 1;Ka();S=Mc;Y=[];X=null;Lc="number"==typeof devicePixelRatio&&devicePixelRatio||
1;window.addEventListener("gamepadconnected",Rc,!0);window.addEventListener("gamepaddisconnected",Tc,!0);window.addEventListener("keydown",Uc,!0);window.addEventListener("keypress",Pc,!0);window.addEventListener("keyup",Vc,!0);window.addEventListener("blur",Wc,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Lc="number"==typeof devicePixelRatio&&devicePixelRatio||1;X&&X.xb&&O(X.xb)(X.id,Lc,Lc)})();f.canvas.addEventListener("touchmove",
Xc,!0);f.canvas.addEventListener("touchstart",ad,!0);f.canvas.addEventListener("touchcancel",bd,!0);f.canvas.addEventListener("touchend",bd,!0);f.canvas.addEventListener("mousemove",Xc,!0);f.canvas.addEventListener("mousedown",ad,!0);f.canvas.addEventListener("mouseup",bd,!0);f.canvas.addEventListener("wheel",cd,!0);f.canvas.addEventListener("mousewheel",cd,!0);f.canvas.addEventListener("mouseenter",Yc,!0);f.canvas.addEventListener("mouseleave",Zc,!0);f.canvas.addEventListener("drop",gd,!0);f.canvas.addEventListener("dragover",
hd,!0);wb.push((b,c)=>{if(X){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.sb=X.x,X.tb=X.y,X.rb=X.width,X.qb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.Ua=!0):1==X.Ua?(X.x=X.sb,X.y=X.tb,X.width=X.rb,X.height=X.qb,X.Ua=!1):X.width!=b||X.height!=c?(X.width=b,X.height=c):d=!1;d&&(xb(X.width,X.height,!0),X&&X.yb&&O(X.yb)(X.id,X.width,X.height),X&&X.hb&&O(X.hb)(X.id,X.width,X.height))}});return 1},X:function(){},M:function(){},
U:function(a,b){if(a=0>=a||!Y?null:Y[a-1]){var c=a.Na;a.Na=b;b=c}else b=null;return b},N:function(){},Y:function(){window.removeEventListener("gamepadconnected",Rc,!0);window.removeEventListener("gamepaddisconnected",Tc,!0);window.removeEventListener("keydown",Uc,!0);window.removeEventListener("keypress",Pc,!0);window.removeEventListener("keyup",Vc,!0);window.removeEventListener("blur",Wc,!0);f.canvas.removeEventListener("touchmove",Xc,!0);f.canvas.removeEventListener("touchstart",ad,!0);f.canvas.removeEventListener("touchcancel",
bd,!0);f.canvas.removeEventListener("touchend",bd,!0);f.canvas.removeEventListener("mousemove",Xc,!0);f.canvas.removeEventListener("mousedown",ad,!0);f.canvas.removeEventListener("mouseup",bd,!0);f.canvas.removeEventListener("wheel",cd,!0);f.canvas.removeEventListener("mousewheel",cd,!0);f.canvas.removeEventListener("mouseenter",Yc,!0);f.canvas.removeEventListener("mouseleave",Zc,!0);f.canvas.removeEventListener("drop",gd,!0);f.canvas.removeEventListener("dragover",hd,!0);f.canvas.width=f.canvas.height=
1;X=Y=null},v:function(a,b){S[a]=b}};
(function(){function a(c){c=c.exports;f.asm=c;la=f.asm.aa;qa();ra=f.asm.ha;ta.unshift(f.asm.ba);D--;f.monitorRunDependencies&&f.monitorRunDependencies(D);if(0==D&&(null!==xa&&(clearInterval(xa),xa=null),ya)){var d=ya;ya=null;d()}return c}var b={a:jd};D++;f.monitorRunDependencies&&f.monitorRunDependencies(D);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return r("Module.instantiateWasm callback failed with error: "+c),!1}Ea(b,function(c){a(c.instance)});return{}})();
f._gl_test=function(){return(f._gl_test=f.asm.ca).apply(null,arguments)};f._add=function(){return(f._add=f.asm.da).apply(null,arguments)};f._list=function(){return(f._list=f.asm.ea).apply(null,arguments)};f._liststr=function(){return(f._liststr=f.asm.fa).apply(null,arguments)};var kd=f._main=function(){return(kd=f._main=f.asm.ga).apply(null,arguments)},Sb=f._malloc=function(){return(Sb=f._malloc=f.asm.ia).apply(null,arguments)},fd=f._free=function(){return(fd=f._free=f.asm.ja).apply(null,arguments)};
function ld(){return(ld=f.asm.ka).apply(null,arguments)}function md(){return(md=f.asm.la).apply(null,arguments)}function nd(){return(nd=f.asm.ma).apply(null,arguments)}
f.ccall=function(a,b,c,d){var e={string:p=>{var t=0;if(null!==p&&void 0!==p&&0!==p){t=Qb(p)+1;var u=nd(t);Mb(p,z,u,t);t=u}return t},array:p=>{var t=nd(p.length);y.set(p,t);return t}};a=f["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var q=e[c[m]];q?(0===h&&(h=ld()),g[m]=q(d[m])):g[m]=d[m]}c=a.apply(null,g);return c=function(p){0!==h&&md(h);return"string"===b?G(p):"boolean"===b?!!p:p}(c)};var od;ya=function pd(){od||rd();od||(ya=pd)};
function rd(){function a(){if(!od&&(od=!0,f.calledRun=!0,!w)){f.noFSInit||Hc||(Hc=!0,Gc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Kc("stdin",f.stdin):Cc("/dev/tty","/dev/stdin"),f.stdout?Kc("stdout",null,f.stdout):Cc("/dev/tty","/dev/stdout"),f.stderr?Kc("stderr",null,f.stderr):Cc("/dev/tty1","/dev/stderr"),Ec("/dev/stdin",0),Ec("/dev/stdout",1),Ec("/dev/stderr",1));pc=!1;Fa(ta);Fa(ua);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(sd){var b=kd;try{var c=b(0,0);ma=c;Ma(c)}catch(d){La(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),va.unshift(b);Fa(va)}}if(!(0<D)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Fa(sa);0<D||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var sd=!0;f.noInitialRun&&(sd=!1);rd();
